# CIF -> MOFid + MOFKey + MOFJSON batch conversion

In [1]:
import sys
import json
import time
from pathlib import Path


def _find_project_root(start: Path) -> Path:
    for candidate in [start, *start.parents]:
        if (candidate / "src" / "mofjson").is_dir():
            return candidate
    raise RuntimeError(f"no src/mofjson found above {start}")


PROJECT_ROOT = _find_project_root(Path.cwd())
sys.path.insert(0, str(PROJECT_ROOT))

from mofid_mofjson_workers import run_mofid_on_cif, run_mofjson_on_cif

MOFID_ASSETS_DIR = Path.cwd() / "mofid_web_assets"

In [2]:
CIF_DIR = Path("/Users/yong/projects/MoFJSON/dataset/CoreMOFDB/CR/")          # <-- edit this
OUTPUT_DIR = Path.cwd() / "mof_conversion_out"
MOFJSON_DIR = OUTPUT_DIR / "mofjson_data/"
RESULTS_JSONL = OUTPUT_DIR / "results.jsonl"   # resumable working file
RESULTS_TABLE = OUTPUT_DIR / "mof_conversion.tsv"

MOFID_TIMEOUT_SECONDS = 120
MOFJSON_TIMEOUT_SECONDS = 120

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
MOFJSON_DIR.mkdir(parents=True, exist_ok=True)

cif_paths = sorted(CIF_DIR.glob("*.cif"))
print(f"{len(cif_paths)} CIFs found in {CIF_DIR}")

2737 CIFs found in /Users/yong/projects/MoFJSON/dataset/CoreMOFDB/CR

In [3]:
# resumable: skip filenames already in results.jsonl
done = set()
if RESULTS_JSONL.exists():
    with open(RESULTS_JSONL) as f:
        for line in f:
            if line.strip():
                done.add(json.loads(line)["cif_filename"])
print(f"{len(done)} already converted, skipping those")

2737 already converted, skipping those

In [4]:
todo = [p for p in cif_paths if p.name not in done]
t0 = time.time()

with open(RESULTS_JSONL, "a") as out:
    for i, cif_path in enumerate(todo):
        row = {"cif_filename": cif_path.name}

        mofid_res = run_mofid_on_cif(str(cif_path), str(MOFID_ASSETS_DIR), MOFID_TIMEOUT_SECONDS)
        if mofid_res["status"] == "ok":
            row["mofid"] = mofid_res["result"]["mofid"]
            row["mofkey"] = mofid_res["result"]["mofkey"]
        else:
            row["mofid"] = None
            row["mofkey"] = None
            row["mofid_error"] = mofid_res["error"]

        mofjson_path = MOFJSON_DIR / (cif_path.stem + ".mofjson.json")
        mofjson_res = run_mofjson_on_cif(str(cif_path), str(PROJECT_ROOT), str(mofjson_path), MOFJSON_TIMEOUT_SECONDS)
        if mofjson_res["status"] == "ok":
            row["mofjson_path"] = str(mofjson_path)
        else:
            row["mofjson_path"] = None
            row["mofjson_error"] = mofjson_res["error"]

        out.write(json.dumps(row) + "\n")
        out.flush()

        if (i + 1) % 25 == 0:
            elapsed = time.time() - t0
            rate = (i + 1) / elapsed
            remaining = (len(todo) - (i + 1)) / rate
            print(f"[{i + 1}/{len(todo)}] ({elapsed:.0f}s elapsed, ~{remaining/60:.0f} min left)")

print(f"done: {len(todo)} converted this run")

[17:18:26] Explicit valence for atom # 68 C, 5, is greater than permitted
[17:18:26] Explicit valence for atom # 68 C, 5, is greater than permitted
[17:18:26] Explicit valence for atom # 68 C, 5, is greater than permitted
[17:18:29] Explicit valence for atom # 68 C, 5, is greater than permitted
[17:18:29] Explicit valence for atom # 68 C, 5, is greater than permitted
[17:18:29] Explicit valence for atom # 68 C, 5, is greater than permitted

[25/2737] (42s elapsed, ~77 min left)

[17:19:05] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:19:05] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:19:05] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:19:05] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:19:06] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:19:06] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:19:06] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:19:06] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:19:33] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:19:33] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:19:33] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:19:33] Explicit valence for atom # 9 C, 5, is greater than permitted

[50/2737] (79s elapsed, ~70 min left)

[17:19:39] Explicit valence for atom # 22 C, 5, is greater than permitted
[17:19:39] Explicit valence for atom # 22 C, 5, is greater than permitted
[17:19:39] Explicit valence for atom # 22 C, 5, is greater than permitted
[17:19:39] Explicit valence for atom # 22 C, 5, is greater than permitted
[17:19:39] Explicit valence for atom # 22 C, 5, is greater than permitted
[17:19:39] Explicit valence for atom # 22 C, 5, is greater than permitted
[17:19:39] Explicit valence for atom # 22 C, 5, is greater than permitted
[17:19:39] Explicit valence for atom # 22 C, 5, is greater than permitted
[17:19:40] Explicit valence for atom # 22 C, 5, is greater than permitted
[17:19:40] Explicit valence for atom # 22 C, 5, is greater than permitted
[17:19:40] Explicit valence for atom # 22 C, 5, is greater than permitted
[17:19:40] Explicit valence for atom # 22 C, 5, is greater than permitted
[17:19:40] Explicit valence for atom # 22 C, 5, is greater than permitted
[17:19:40] Explicit valence for atom # 22 C, 5, is greater than permitted
[17:19:40] Explicit valence for atom # 22 C, 5, is greater than permitted
[17:19:40] Explicit valence for atom # 22 C, 5, is greater than permitted
[17:20:00] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:20:00] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:20:00] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:20:00] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:20:02] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:20:02] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:20:02] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:20:02] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:20:04] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:20:04] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:20:04] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:20:04] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:20:04] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:20:04] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:20:04] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:20:04] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:20:04] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:20:04] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:20:04] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:20:04] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:20:04] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:20:04] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:20:04] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:20:04] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:20:07] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:20:07] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:20:07] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:20:07] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:20:07] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:20:07] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:20:07] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:20:07] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:20:08] Explicit valence for atom # 21 C, 5, is greater than permitted
[17:20:08] Explicit valence for atom # 21 C, 5, is greater than permitted
[17:20:10] Explicit valence for atom # 21 C, 5, is greater than permitted
[17:20:10] Explicit valence for atom # 21 C, 5, is greater than permitted
[17:20:11] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:20:11] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:20:11] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:20:11] Explicit valence for atom # 9 C, 5, is greater than permitted

[75/2737] (117s elapsed, ~69 min left)

[17:20:19] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:20:19] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:20:21] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:20:21] Explicit valence for atom # 11 C, 5, is greater than permitted

[100/2737] (160s elapsed, ~70 min left)

[17:21:07] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:07] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:07] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:07] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:08] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:08] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:08] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:08] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:09] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:09] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:09] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:09] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:11] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:11] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:11] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:11] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:15] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:15] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:15] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:15] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:16] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:16] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:16] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:16] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:23] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:23] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:23] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:23] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:24] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:24] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:24] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:24] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:26] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:26] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:26] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:26] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:27] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:27] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:27] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:21:27] Explicit valence for atom # 0 N, 4, is greater than permitted

[125/2737] (201s elapsed, ~70 min left)

[17:21:38] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:21:38] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:21:38] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:21:38] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:21:38] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:21:38] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:21:38] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:21:38] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:21:38] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:21:38] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:21:38] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:21:38] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:21:50] Explicit valence for atom # 21 C, 5, is greater than permitted
[17:21:50] Explicit valence for atom # 21 C, 5, is greater than permitted
[17:21:50] Explicit valence for atom # 21 C, 5, is greater than permitted
[17:21:50] Explicit valence for atom # 21 C, 5, is greater than permitted
[17:21:50] Explicit valence for atom # 21 C, 5, is greater than permitted
[17:21:50] Explicit valence for atom # 21 C, 5, is greater than permitted
[17:21:50] Explicit valence for atom # 21 C, 5, is greater than permitted
[17:21:50] Explicit valence for atom # 21 C, 5, is greater than permitted
[17:21:52] Explicit valence for atom # 21 C, 5, is greater than permitted
[17:21:52] Explicit valence for atom # 21 C, 5, is greater than permitted
[17:21:52] Explicit valence for atom # 21 C, 5, is greater than permitted
[17:21:52] Explicit valence for atom # 21 C, 5, is greater than permitted
[17:21:52] Explicit valence for atom # 21 C, 5, is greater than permitted
[17:21:52] Explicit valence for atom # 21 C, 5, is greater than permitted
[17:21:52] Explicit valence for atom # 21 C, 5, is greater than permitted
[17:21:52] Explicit valence for atom # 21 C, 5, is greater than permitted
[17:22:00] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:22:00] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:22:00] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:22:00] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:22:03] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:22:03] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:22:03] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:22:03] Explicit valence for atom # 7 C, 5, is greater than permitted

[150/2737] (243s elapsed, ~70 min left)

[17:22:31] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:22:31] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:22:33] Explicit valence for atom # 22 C, 5, is greater than permitted
[17:22:33] Explicit valence for atom # 22 C, 5, is greater than permitted
[17:22:33] Explicit valence for atom # 22 C, 5, is greater than permitted
[17:22:33] Explicit valence for atom # 22 C, 5, is greater than permitted
[17:22:35] Explicit valence for atom # 22 C, 5, is greater than permitted
[17:22:35] Explicit valence for atom # 22 C, 5, is greater than permitted
[17:22:35] Explicit valence for atom # 22 C, 5, is greater than permitted
[17:22:35] Explicit valence for atom # 22 C, 5, is greater than permitted
[17:22:47] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:47] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:47] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:47] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:47] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:47] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:47] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:47] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:47] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:47] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:47] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:47] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:48] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:48] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:48] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:48] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:48] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:48] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:48] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:48] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:48] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:48] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:48] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:48] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:49] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:49] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:49] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:49] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:49] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:49] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:49] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:49] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:49] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:49] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:49] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:49] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:50] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:50] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:50] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:50] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:50] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:50] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:50] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:50] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:50] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:50] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:50] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:22:50] Explicit valence for atom # 0 N, 4, is greater than permitted

[175/2737] (280s elapsed, ~68 min left)

[17:23:03] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:23:03] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:23:04] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:23:04] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:23:10] Explicit valence for atom # 3 H, 2, is greater than permitted
[17:23:11] Explicit valence for atom # 3 H, 2, is greater than permitted
[17:23:23] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:23:23] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:23:23] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:23:23] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:23:23] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:23:23] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:23:23] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:23:23] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:23:23] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:23:23] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:23:23] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:23:23] Explicit valence for atom # 7 C, 5, is greater than permitted

[200/2737] (316s elapsed, ~67 min left)

[17:23:36] Explicit valence for atom # 68 C, 5, is greater than permitted
[17:23:36] Explicit valence for atom # 68 C, 5, is greater than permitted
[17:23:36] Explicit valence for atom # 68 C, 5, is greater than permitted
[17:23:36] Explicit valence for atom # 68 C, 5, is greater than permitted
[17:23:39] Explicit valence for atom # 0 N, 5, is greater than permitted
[17:23:39] Explicit valence for atom # 0 N, 5, is greater than permitted
[17:23:39] Explicit valence for atom # 0 N, 5, is greater than permitted
[17:23:39] Explicit valence for atom # 0 N, 5, is greater than permitted
[17:23:40] Explicit valence for atom # 0 N, 5, is greater than permitted
[17:23:40] Explicit valence for atom # 0 N, 5, is greater than permitted
[17:23:40] Explicit valence for atom # 0 N, 5, is greater than permitted
[17:23:40] Explicit valence for atom # 0 N, 5, is greater than permitted
[17:23:42] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:23:42] Explicit valence for atom # 4 C, 5, is greater than permitted
[17:23:42] Explicit valence for atom # 4 C, 5, is greater than permitted
[17:23:42] Explicit valence for atom # 4 C, 5, is greater than permitted
[17:23:42] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:23:42] Explicit valence for atom # 4 C, 5, is greater than permitted
[17:23:44] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:23:44] Explicit valence for atom # 4 C, 5, is greater than permitted
[17:23:44] Explicit valence for atom # 4 C, 5, is greater than permitted
[17:23:44] Explicit valence for atom # 4 C, 5, is greater than permitted
[17:23:44] Explicit valence for atom # 1 C, 5, is greater than permitted
[17:23:44] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:23:44] Explicit valence for atom # 1 C, 5, is greater than permitted
[17:23:44] Explicit valence for atom # 1 C, 5, is greater than permitted
[17:23:44] Explicit valence for atom # 1 C, 5, is greater than permitted
[17:23:44] Explicit valence for atom # 4 C, 5, is greater than permitted
[17:23:52] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:23:52] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:23:52] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:23:52] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:26:37] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:26:37] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:27:38] Explicit valence for atom # 0 N, 5, is greater than permitted
[17:27:38] Explicit valence for atom # 0 N, 5, is greater than permitted

[225/2737] (570s elapsed, ~106 min left)
[250/2737] (606s elapsed, ~100 min left)

[17:28:27] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:28:27] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:28:29] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:28:29] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:28:45] Explicit valence for atom # 7 C, 6, is greater than permitted
[17:28:45] Explicit valence for atom # 7 C, 6, is greater than permitted
[17:28:52] Explicit valence for atom # 7 C, 6, is greater than permitted
[17:28:52] Explicit valence for atom # 7 C, 6, is greater than permitted
[17:28:56] Explicit valence for atom # 14 C, 5, is greater than permitted
[17:28:56] Explicit valence for atom # 14 C, 5, is greater than permitted
[17:28:59] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:28:59] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:28:59] Explicit valence for atom # 14 C, 5, is greater than permitted
[17:28:59] Explicit valence for atom # 14 C, 5, is greater than permitted
[17:29:03] Explicit valence for atom # 7 C, 6, is greater than permitted
[17:29:03] Explicit valence for atom # 7 C, 6, is greater than permitted
[17:29:14] Explicit valence for atom # 7 C, 6, is greater than permitted
[17:29:14] Explicit valence for atom # 7 C, 6, is greater than permitted
[17:29:14] Explicit valence for atom # 7 C, 6, is greater than permitted
[17:29:14] Explicit valence for atom # 7 C, 6, is greater than permitted
[17:29:19] Explicit valence for atom # 7 C, 6, is greater than permitted
[17:29:19] Explicit valence for atom # 7 C, 6, is greater than permitted
[17:29:19] Explicit valence for atom # 7 C, 6, is greater than permitted
[17:29:19] Explicit valence for atom # 7 C, 6, is greater than permitted

[275/2737] (667s elapsed, ~100 min left)

[17:29:56] Explicit valence for atom # 22 C, 5, is greater than permitted
[17:29:56] Explicit valence for atom # 22 C, 5, is greater than permitted
[17:29:56] Explicit valence for atom # 22 C, 5, is greater than permitted
[17:29:56] Explicit valence for atom # 22 C, 5, is greater than permitted

[300/2737] (708s elapsed, ~96 min left)

[17:30:08] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:30:08] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:30:09] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:30:09] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:30:17] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:30:17] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:30:17] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:30:17] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:30:17] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:30:17] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:30:17] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:30:17] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:30:25] Explicit valence for atom # 13 N, 4, is greater than permitted
[17:30:25] Explicit valence for atom # 13 N, 4, is greater than permitted
[17:30:25] Explicit valence for atom # 13 N, 4, is greater than permitted
[17:30:25] Explicit valence for atom # 13 N, 4, is greater than permitted
[17:30:25] Explicit valence for atom # 13 N, 4, is greater than permitted
[17:30:25] Explicit valence for atom # 13 N, 4, is greater than permitted
[17:30:25] Explicit valence for atom # 13 N, 4, is greater than permitted
[17:30:25] Explicit valence for atom # 13 N, 4, is greater than permitted
[17:30:32] Explicit valence for atom # 18 C, 5, is greater than permitted
[17:30:32] Explicit valence for atom # 18 C, 5, is greater than permitted
[17:30:32] Explicit valence for atom # 18 C, 5, is greater than permitted
[17:30:32] Explicit valence for atom # 18 C, 5, is greater than permitted
[17:30:33] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:30:33] Explicit valence for atom # 18 C, 5, is greater than permitted
[17:30:33] Explicit valence for atom # 18 C, 5, is greater than permitted
[17:30:33] Explicit valence for atom # 18 C, 5, is greater than permitted
[17:30:33] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:30:33] Explicit valence for atom # 18 C, 5, is greater than permitted
[17:30:34] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:30:34] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:30:34] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:30:34] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:30:34] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:30:34] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:30:34] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:30:34] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:30:35] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:30:35] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:30:35] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:30:35] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:30:35] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:30:35] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:30:35] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:30:35] Explicit valence for atom # 17 C, 5, is greater than permitted

[325/2737] (743s elapsed, ~92 min left)

[17:30:39] Explicit valence for atom # 24 C, 5, is greater than permitted
[17:30:39] Explicit valence for atom # 10 C, 6, is greater than permitted
[17:30:39] Explicit valence for atom # 10 C, 6, is greater than permitted
[17:30:39] Explicit valence for atom # 24 C, 5, is greater than permitted
[17:30:39] Explicit valence for atom # 10 C, 6, is greater than permitted
[17:30:39] Explicit valence for atom # 10 C, 6, is greater than permitted
[17:30:41] Explicit valence for atom # 24 C, 5, is greater than permitted
[17:30:41] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:30:41] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:30:41] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:30:41] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:30:41] Explicit valence for atom # 10 C, 6, is greater than permitted
[17:30:41] Explicit valence for atom # 10 C, 6, is greater than permitted
[17:30:41] Explicit valence for atom # 24 C, 5, is greater than permitted
[17:30:41] Explicit valence for atom # 10 C, 6, is greater than permitted
[17:30:41] Explicit valence for atom # 10 C, 6, is greater than permitted
[17:30:55] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:30:55] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:30:57] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:30:57] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:30:57] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:30:57] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:30:57] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:30:57] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:31:10] Explicit valence for atom # 15 C, 5, is greater than permitted

[350/2737] (778s elapsed, ~88 min left)

[17:31:32] Explicit valence for atom # 6 C, 5, is greater than permitted
[17:31:32] Explicit valence for atom # 6 C, 5, is greater than permitted
[17:31:33] Explicit valence for atom # 6 C, 5, is greater than permitted
[17:31:33] Explicit valence for atom # 6 C, 5, is greater than permitted

[375/2737] (816s elapsed, ~86 min left)
[400/2737] (855s elapsed, ~83 min left)

[17:32:41] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:32:41] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:32:41] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:32:41] Explicit valence for atom # 9 C, 5, is greater than permitted

[425/2737] (893s elapsed, ~81 min left)

[17:33:13] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:13] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:13] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:13] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:13] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:13] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:13] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:13] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:13] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:13] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:13] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:13] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:13] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:13] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:13] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:13] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:13] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:13] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:13] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:13] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:13] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:13] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:13] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:13] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:17] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:17] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:17] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:17] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:17] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:17] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:17] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:17] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:17] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:17] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:17] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:17] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:17] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:17] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:17] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:17] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:17] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:17] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:17] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:17] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:17] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:17] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:17] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:17] Explicit valence for atom # 13 C, 5, is greater than permitted
[17:33:21] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:33:21] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:33:23] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:33:23] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:33:24] Explicit valence for atom # 67 N, 4, is greater than permitted
[17:33:24] Explicit valence for atom # 67 N, 4, is greater than permitted
[17:33:24] Explicit valence for atom # 67 N, 4, is greater than permitted
[17:33:24] Explicit valence for atom # 67 N, 4, is greater than permitted
[17:33:26] Explicit valence for atom # 67 N, 4, is greater than permitted
[17:33:26] Explicit valence for atom # 67 N, 4, is greater than permitted
[17:33:26] Explicit valence for atom # 67 N, 4, is greater than permitted
[17:33:26] Explicit valence for atom # 67 N, 4, is greater than permitted
[17:33:28] Explicit valence for atom # 44 C, 6, is greater than permitted
[17:33:28] Explicit valence for atom # 44 C, 6, is greater than permitted
[17:33:28] Explicit valence for atom # 44 C, 6, is greater than permitted
[17:33:28] Explicit valence for atom # 44 C, 6, is greater than permitted
[17:33:28] Explicit valence for atom # 44 C, 6, is greater than permitted
[17:33:28] Explicit valence for atom # 44 C, 6, is greater than permitted
[17:33:28] Explicit valence for atom # 44 C, 6, is greater than permitted
[17:33:28] Explicit valence for atom # 44 C, 6, is greater than permitted
[17:33:31] Explicit valence for atom # 44 C, 6, is greater than permitted
[17:33:31] Explicit valence for atom # 44 C, 6, is greater than permitted
[17:33:31] Explicit valence for atom # 44 C, 6, is greater than permitted
[17:33:31] Explicit valence for atom # 44 C, 6, is greater than permitted
[17:33:31] Explicit valence for atom # 44 C, 6, is greater than permitted
[17:33:31] Explicit valence for atom # 44 C, 6, is greater than permitted
[17:33:31] Explicit valence for atom # 44 C, 6, is greater than permitted
[17:33:31] Explicit valence for atom # 44 C, 6, is greater than permitted
[17:33:38] Explicit valence for atom # 4 C, 6, is greater than permitted
[17:33:38] Explicit valence for atom # 4 C, 6, is greater than permitted
[17:33:40] Explicit valence for atom # 4 C, 6, is greater than permitted
[17:33:40] Explicit valence for atom # 4 C, 6, is greater than permitted

[450/2737] (935s elapsed, ~79 min left)

[17:34:04] Explicit valence for atom # 9 N, 4, is greater than permitted
[17:34:04] Explicit valence for atom # 9 N, 4, is greater than permitted
[17:34:22] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:34:22] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:34:22] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:34:22] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:34:27] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:34:27] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:34:27] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:34:27] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:34:28] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:34:28] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:34:28] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:34:28] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:34:29] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:34:29] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:34:29] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:34:29] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:34:31] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:34:31] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:34:31] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:34:31] Explicit valence for atom # 11 C, 5, is greater than permitted

[475/2737] (977s elapsed, ~78 min left)

[17:34:32] Explicit valence for atom # 18 C, 5, is greater than permitted
[17:34:32] Explicit valence for atom # 18 C, 5, is greater than permitted
[17:34:32] Explicit valence for atom # 18 C, 5, is greater than permitted
[17:34:32] Explicit valence for atom # 18 C, 5, is greater than permitted
[17:34:34] Explicit valence for atom # 18 C, 5, is greater than permitted
[17:34:34] Explicit valence for atom # 18 C, 5, is greater than permitted
[17:34:34] Explicit valence for atom # 18 C, 5, is greater than permitted
[17:34:34] Explicit valence for atom # 18 C, 5, is greater than permitted
[17:34:35] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:34:35] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:34:37] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:34:37] Explicit valence for atom # 10 N, 4, is greater than permitted
[17:34:37] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:34:37] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:34:37] Explicit valence for atom # 10 N, 4, is greater than permitted
[17:34:37] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:34:37] Explicit valence for atom # 10 N, 4, is greater than permitted
[17:34:37] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:34:37] Explicit valence for atom # 10 N, 4, is greater than permitted
[17:34:37] Explicit valence for atom # 3 C, 5, is greater than permitted

[500/2737] (1009s elapsed, ~75 min left)

[17:35:19] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:35:19] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:35:19] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:35:19] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:35:19] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:35:19] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:35:19] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:35:19] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:35:26] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:35:26] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:35:26] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:35:26] Explicit valence for atom # 20 N, 4, is greater than permitted
[17:35:27] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:35:27] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:35:27] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:35:27] Explicit valence for atom # 20 N, 4, is greater than permitted
[17:35:38] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 1 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 1 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 1 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 1 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 1 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 1 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 1 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 1 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 1 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 1 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 1 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 1 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:38] Explicit valence for atom # 0 C, 5, is greater than permitted

[525/2737] (1044s elapsed, ~73 min left)

[17:35:39] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 1 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 1 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 1 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 1 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 1 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 1 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 1 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 1 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 1 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 1 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 1 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 1 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:39] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:35:50] Explicit valence for atom # 8 C, 5, is greater than permitted
[17:35:50] Explicit valence for atom # 8 C, 5, is greater than permitted
[17:35:50] Explicit valence for atom # 8 C, 5, is greater than permitted
[17:35:50] Explicit valence for atom # 8 C, 5, is greater than permitted
[17:35:59] Explicit valence for atom # 62 C, 5, is greater than permitted
[17:35:59] Explicit valence for atom # 62 C, 5, is greater than permitted
[17:36:01] Explicit valence for atom # 62 C, 5, is greater than permitted
[17:36:01] Explicit valence for atom # 62 C, 5, is greater than permitted
[17:36:04] Explicit valence for atom # 9 N, 4, is greater than permitted
[17:36:04] Explicit valence for atom # 9 N, 4, is greater than permitted
[17:36:04] Explicit valence for atom # 9 N, 4, is greater than permitted
[17:36:04] Explicit valence for atom # 10 O, 3, is greater than permitted
[17:36:04] Explicit valence for atom # 10 O, 3, is greater than permitted
[17:36:04] Explicit valence for atom # 10 O, 3, is greater than permitted
[17:36:04] Explicit valence for atom # 10 O, 3, is greater than permitted
[17:36:04] Explicit valence for atom # 9 N, 4, is greater than permitted
[17:36:06] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:36:06] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:36:07] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:36:07] Explicit valence for atom # 19 C, 5, is greater than permitted

[550/2737] (1080s elapsed, ~72 min left)

[17:36:18] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:36:18] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:36:18] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:36:18] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:36:34] Explicit valence for atom # 32 C, 5, is greater than permitted
[17:36:34] Explicit valence for atom # 32 C, 5, is greater than permitted
[17:36:34] Explicit valence for atom # 32 C, 5, is greater than permitted
[17:36:34] Explicit valence for atom # 32 C, 5, is greater than permitted
[17:36:34] Explicit valence for atom # 32 C, 5, is greater than permitted
[17:36:34] Explicit valence for atom # 32 C, 5, is greater than permitted
[17:36:34] Explicit valence for atom # 32 C, 5, is greater than permitted
[17:36:34] Explicit valence for atom # 32 C, 5, is greater than permitted
[17:36:46] Explicit valence for atom # 24 C, 5, is greater than permitted
[17:36:46] Explicit valence for atom # 24 C, 5, is greater than permitted
[17:36:47] Explicit valence for atom # 24 C, 5, is greater than permitted
[17:36:47] Explicit valence for atom # 24 C, 5, is greater than permitted

[575/2737] (1115s elapsed, ~70 min left)

[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:37:23] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:37:23] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:37:23] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:37:23] Explicit valence for atom # 12 C, 6, is greater than permitted
[17:37:23] Explicit valence for atom # 12 C, 6, is greater than permitted
[17:37:23] Explicit valence for atom # 11 C, 5, is greater than permitted

[600/2737] (1158s elapsed, ~69 min left)

[17:38:02] Explicit valence for atom # 33 C, 5, is greater than permitted
[17:38:02] Explicit valence for atom # 33 C, 5, is greater than permitted
[17:38:02] Explicit valence for atom # 4 C, 5, is greater than permitted
[17:38:02] Explicit valence for atom # 4 C, 5, is greater than permitted
[17:38:02] Explicit valence for atom # 4 C, 5, is greater than permitted
[17:38:02] Explicit valence for atom # 4 C, 5, is greater than permitted
[17:38:03] Explicit valence for atom # 33 C, 5, is greater than permitted
[17:38:03] Explicit valence for atom # 33 C, 5, is greater than permitted
[17:38:03] Explicit valence for atom # 4 C, 5, is greater than permitted
[17:38:03] Explicit valence for atom # 4 C, 5, is greater than permitted
[17:38:03] Explicit valence for atom # 4 C, 5, is greater than permitted
[17:38:03] Explicit valence for atom # 4 C, 5, is greater than permitted

[625/2737] (1196s elapsed, ~67 min left)

[17:38:33] Explicit valence for atom # 16 C, 5, is greater than permitted
[17:38:33] Explicit valence for atom # 16 C, 5, is greater than permitted
[17:38:33] Explicit valence for atom # 16 C, 5, is greater than permitted
[17:38:33] Explicit valence for atom # 16 C, 5, is greater than permitted
[17:38:33] Explicit valence for atom # 16 C, 5, is greater than permitted
[17:38:33] Explicit valence for atom # 16 C, 5, is greater than permitted
[17:38:33] Explicit valence for atom # 16 C, 5, is greater than permitted
[17:38:33] Explicit valence for atom # 16 C, 5, is greater than permitted
[17:38:46] Explicit valence for atom # 15 C, 5, is greater than permitted
[17:38:46] Explicit valence for atom # 15 C, 5, is greater than permitted
[17:38:46] Explicit valence for atom # 15 C, 5, is greater than permitted
[17:38:46] Explicit valence for atom # 15 C, 5, is greater than permitted
[17:38:46] Explicit valence for atom # 15 C, 5, is greater than permitted
[17:38:46] Explicit valence for atom # 15 C, 5, is greater than permitted
[17:38:46] Explicit valence for atom # 15 C, 5, is greater than permitted
[17:38:46] Explicit valence for atom # 15 C, 5, is greater than permitted

[650/2737] (1234s elapsed, ~66 min left)

[17:38:49] Explicit valence for atom # 9 C, 6, is greater than permitted
[17:38:49] Explicit valence for atom # 9 C, 6, is greater than permitted
[17:38:49] Explicit valence for atom # 9 C, 6, is greater than permitted
[17:38:49] Explicit valence for atom # 9 C, 6, is greater than permitted
[17:39:23] Explicit valence for atom # 0 H, 3, is greater than permitted
[17:39:29] Explicit valence for atom # 0 H, 3, is greater than permitted

[675/2737] (1396s elapsed, ~71 min left)
[700/2737] (1431s elapsed, ~69 min left)

[17:42:07] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:42:07] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:42:07] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:42:07] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:42:07] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:42:07] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:42:07] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:42:07] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:42:27] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:42:27] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:42:27] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:42:27] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:42:27] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:42:27] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:42:27] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:42:27] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:42:29] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:42:29] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:42:29] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:42:29] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:42:29] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:42:29] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:42:29] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:42:29] Explicit valence for atom # 7 C, 5, is greater than permitted

[725/2737] (1458s elapsed, ~67 min left)

[17:42:36] Explicit valence for atom # 24 C, 5, is greater than permitted
[17:42:38] Explicit valence for atom # 24 C, 5, is greater than permitted
[17:42:43] Explicit valence for atom # 21 C, 5, is greater than permitted
[17:42:43] Explicit valence for atom # 21 C, 5, is greater than permitted
[17:42:43] Explicit valence for atom # 21 C, 5, is greater than permitted
[17:42:43] Explicit valence for atom # 21 C, 5, is greater than permitted
[17:42:45] Explicit valence for atom # 21 C, 5, is greater than permitted
[17:42:45] Explicit valence for atom # 21 C, 5, is greater than permitted
[17:42:45] Explicit valence for atom # 21 C, 5, is greater than permitted
[17:42:45] Explicit valence for atom # 21 C, 5, is greater than permitted
[17:42:49] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:42:49] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:42:49] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:42:49] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:43:00] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:43:00] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:43:00] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:43:00] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:43:00] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:43:00] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:43:00] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:43:00] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:43:00] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:43:00] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:43:00] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:43:00] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:43:07] Explicit valence for atom # 24 C, 5, is greater than permitted
[17:43:07] Explicit valence for atom # 24 C, 5, is greater than permitted
[17:43:07] Explicit valence for atom # 24 C, 5, is greater than permitted
[17:43:07] Explicit valence for atom # 24 C, 5, is greater than permitted
[17:43:07] Explicit valence for atom # 14 C, 5, is greater than permitted
[17:43:07] Explicit valence for atom # 14 C, 5, is greater than permitted
[17:43:07] Explicit valence for atom # 14 C, 5, is greater than permitted
[17:43:07] Explicit valence for atom # 14 C, 5, is greater than permitted
[17:43:10] Explicit valence for atom # 24 C, 5, is greater than permitted
[17:43:10] Explicit valence for atom # 24 C, 5, is greater than permitted
[17:43:10] Explicit valence for atom # 24 C, 5, is greater than permitted
[17:43:10] Explicit valence for atom # 24 C, 5, is greater than permitted
[17:43:10] Explicit valence for atom # 14 C, 5, is greater than permitted
[17:43:10] Explicit valence for atom # 14 C, 5, is greater than permitted
[17:43:10] Explicit valence for atom # 14 C, 5, is greater than permitted
[17:43:10] Explicit valence for atom # 14 C, 5, is greater than permitted
[17:43:10] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:43:10] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:43:10] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:43:10] Explicit valence for atom # 7 C, 5, is greater than permitted

[750/2737] (1497s elapsed, ~66 min left)

[17:43:25] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:43:25] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:43:25] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:43:25] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:43:26] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:43:26] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:43:26] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:43:26] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:43:28] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:43:28] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:43:28] Explicit valence for atom # 21 N, 4, is greater than permitted
[17:43:28] Explicit valence for atom # 21 N, 4, is greater than permitted
[17:43:30] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:43:30] Explicit valence for atom # 21 N, 4, is greater than permitted
[17:43:30] Explicit valence for atom # 21 N, 4, is greater than permitted
[17:43:30] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:43:37] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:43:37] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:43:37] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:43:37] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:43:38] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:43:38] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:43:38] Explicit valence for atom # 0 C, 5, is greater than permitted
[17:43:38] Explicit valence for atom # 0 C, 5, is greater than permitted

[775/2737] (1537s elapsed, ~65 min left)

[17:43:55] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:43:55] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:43:55] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:43:55] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:44:15] Explicit valence for atom # 14 C, 5, is greater than permitted
[17:44:15] Explicit valence for atom # 16 C, 5, is greater than permitted
[17:44:16] Explicit valence for atom # 14 C, 5, is greater than permitted
[17:44:16] Explicit valence for atom # 16 C, 5, is greater than permitted
[17:44:18] Explicit valence for atom # 27 C, 5, is greater than permitted
[17:44:18] Explicit valence for atom # 27 C, 5, is greater than permitted
[17:44:19] Explicit valence for atom # 27 C, 5, is greater than permitted
[17:44:19] Explicit valence for atom # 27 C, 5, is greater than permitted

[800/2737] (1576s elapsed, ~64 min left)

[17:44:41] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:44:41] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:44:44] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:44:44] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:45:05] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:45:05] Explicit valence for atom # 11 C, 5, is greater than permitted

[825/2737] (1615s elapsed, ~62 min left)

[17:45:31] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:45:31] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:45:31] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:45:31] Explicit valence for atom # 7 C, 5, is greater than permitted

[850/2737] (1652s elapsed, ~61 min left)

[17:45:56] Explicit valence for atom # 16 C, 5, is greater than permitted
[17:45:56] Explicit valence for atom # 16 C, 5, is greater than permitted
[17:45:56] Explicit valence for atom # 16 C, 5, is greater than permitted
[17:45:56] Explicit valence for atom # 16 C, 5, is greater than permitted
[17:45:58] Explicit valence for atom # 16 C, 5, is greater than permitted
[17:45:58] Explicit valence for atom # 16 C, 5, is greater than permitted
[17:45:58] Explicit valence for atom # 16 C, 5, is greater than permitted
[17:45:58] Explicit valence for atom # 16 C, 5, is greater than permitted
[17:46:16] Explicit valence for atom # 9 N, 4, is greater than permitted
[17:46:16] Explicit valence for atom # 9 N, 4, is greater than permitted
[17:46:16] Explicit valence for atom # 9 N, 4, is greater than permitted
[17:46:16] Explicit valence for atom # 9 N, 4, is greater than permitted
[17:46:19] Explicit valence for atom # 23 N, 4, is greater than permitted
[17:46:19] Explicit valence for atom # 23 N, 4, is greater than permitted
[17:46:21] Explicit valence for atom # 23 N, 4, is greater than permitted
[17:46:21] Explicit valence for atom # 23 N, 4, is greater than permitted
[17:46:22] Explicit valence for atom # 23 N, 4, is greater than permitted
[17:46:22] Explicit valence for atom # 23 N, 4, is greater than permitted

[875/2737] (1692s elapsed, ~60 min left)
[900/2737] (1735s elapsed, ~59 min left)

[17:47:11] Explicit valence for atom # 48 H, 2, is greater than permitted
[17:47:12] Explicit valence for atom # 48 H, 2, is greater than permitted
[17:47:50] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:47:50] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:47:50] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:47:50] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:47:51] Explicit valence for atom # 1 C, 6, is greater than permitted
[17:47:51] Explicit valence for atom # 1 C, 6, is greater than permitted
[17:47:51] Explicit valence for atom # 1 C, 6, is greater than permitted
[17:47:51] Explicit valence for atom # 1 C, 6, is greater than permitted
[17:47:53] Explicit valence for atom # 6 C, 5, is greater than permitted
[17:47:53] Explicit valence for atom # 6 C, 5, is greater than permitted
[17:47:53] Explicit valence for atom # 6 C, 6, is greater than permitted
[17:47:53] Explicit valence for atom # 6 C, 6, is greater than permitted

[925/2737] (1779s elapsed, ~58 min left)

[17:47:54] Explicit valence for atom # 6 C, 5, is greater than permitted
[17:47:54] Explicit valence for atom # 6 C, 5, is greater than permitted
[17:47:54] Explicit valence for atom # 6 C, 6, is greater than permitted
[17:47:54] Explicit valence for atom # 6 C, 6, is greater than permitted
[17:48:08] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:48:08] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:48:08] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:48:08] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:48:08] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:48:08] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:48:13] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:48:13] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:48:15] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:48:15] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:48:26] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:48:26] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:48:26] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:48:26] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:48:32] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:48:32] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:48:32] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:48:32] Explicit valence for atom # 7 C, 5, is greater than permitted

[950/2737] (1818s elapsed, ~57 min left)

[17:48:41] Explicit valence for atom # 6 C, 5, is greater than permitted
[17:48:41] Explicit valence for atom # 6 C, 5, is greater than permitted
[17:48:41] Explicit valence for atom # 6 C, 5, is greater than permitted
[17:48:41] Explicit valence for atom # 6 C, 5, is greater than permitted
[17:48:43] Explicit valence for atom # 6 C, 5, is greater than permitted
[17:48:43] Explicit valence for atom # 6 C, 5, is greater than permitted
[17:48:43] Explicit valence for atom # 6 C, 5, is greater than permitted
[17:48:43] Explicit valence for atom # 6 C, 5, is greater than permitted
[17:48:48] Explicit valence for atom # 5 C, 5, is greater than permitted
[17:48:48] Explicit valence for atom # 5 C, 5, is greater than permitted
[17:48:48] Explicit valence for atom # 5 C, 5, is greater than permitted
[17:48:48] Explicit valence for atom # 5 C, 5, is greater than permitted
[17:48:48] Explicit valence for atom # 5 C, 5, is greater than permitted
[17:48:48] Explicit valence for atom # 5 C, 5, is greater than permitted
[17:48:48] Explicit valence for atom # 5 C, 5, is greater than permitted
[17:48:48] Explicit valence for atom # 5 C, 5, is greater than permitted
[17:48:52] Explicit valence for atom # 5 C, 5, is greater than permitted
[17:48:52] Explicit valence for atom # 5 C, 5, is greater than permitted
[17:48:52] Explicit valence for atom # 5 C, 5, is greater than permitted
[17:48:52] Explicit valence for atom # 5 C, 5, is greater than permitted
[17:48:52] Explicit valence for atom # 5 C, 5, is greater than permitted
[17:48:52] Explicit valence for atom # 5 C, 5, is greater than permitted
[17:48:52] Explicit valence for atom # 5 C, 5, is greater than permitted
[17:48:52] Explicit valence for atom # 5 C, 5, is greater than permitted
[17:48:53] Explicit valence for atom # 30 C, 5, is greater than permitted
[17:48:53] Explicit valence for atom # 30 C, 5, is greater than permitted
[17:48:55] Explicit valence for atom # 30 C, 5, is greater than permitted
[17:48:55] Explicit valence for atom # 30 C, 5, is greater than permitted
[17:48:56] Explicit valence for atom # 24 C, 5, is greater than permitted
[17:48:56] Explicit valence for atom # 24 C, 5, is greater than permitted
[17:48:57] Explicit valence for atom # 24 C, 5, is greater than permitted
[17:48:57] Explicit valence for atom # 24 C, 5, is greater than permitted
[17:49:08] Explicit valence for atom # 34 C, 5, is greater than permitted
[17:49:08] Explicit valence for atom # 34 C, 5, is greater than permitted
[17:49:08] Explicit valence for atom # 34 C, 5, is greater than permitted
[17:49:08] Explicit valence for atom # 34 C, 5, is greater than permitted
[17:49:08] Explicit valence for atom # 34 C, 5, is greater than permitted
[17:49:08] Explicit valence for atom # 34 C, 5, is greater than permitted
[17:49:08] Explicit valence for atom # 34 C, 5, is greater than permitted
[17:49:08] Explicit valence for atom # 34 C, 5, is greater than permitted
[17:49:08] Explicit valence for atom # 34 C, 5, is greater than permitted
[17:49:08] Explicit valence for atom # 34 C, 5, is greater than permitted
[17:49:08] Explicit valence for atom # 34 C, 5, is greater than permitted
[17:49:08] Explicit valence for atom # 34 C, 5, is greater than permitted

[975/2737] (1862s elapsed, ~56 min left)

[17:49:17] Explicit valence for atom # 31 C, 5, is greater than permitted
[17:49:17] Explicit valence for atom # 31 C, 5, is greater than permitted
[17:49:17] Explicit valence for atom # 11 N, 5, is greater than permitted
[17:49:17] Explicit valence for atom # 11 N, 5, is greater than permitted
[17:49:19] Explicit valence for atom # 31 C, 5, is greater than permitted
[17:49:19] Explicit valence for atom # 31 C, 5, is greater than permitted
[17:49:19] Explicit valence for atom # 11 N, 5, is greater than permitted
[17:49:19] Explicit valence for atom # 11 N, 5, is greater than permitted
[17:49:23] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:49:23] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:49:23] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:49:23] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:49:23] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:49:23] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:49:23] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:49:23] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:49:23] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:49:23] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:49:23] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:49:23] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:49:26] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:49:26] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:49:26] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:49:26] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:49:26] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:49:26] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:49:26] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:49:26] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:49:26] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:49:26] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:49:26] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:49:26] Explicit valence for atom # 21 N, 5, is greater than permitted
[17:49:30] Explicit valence for atom # 38 C, 5, is greater than permitted
[17:49:30] Explicit valence for atom # 38 C, 5, is greater than permitted
[17:49:32] Explicit valence for atom # 38 C, 5, is greater than permitted
[17:49:32] Explicit valence for atom # 38 C, 5, is greater than permitted

[1000/2737] (1898s elapsed, ~55 min left)

[17:49:53] Explicit valence for atom # 6 C, 6, is greater than permitted
[17:49:53] Explicit valence for atom # 6 C, 6, is greater than permitted
[17:50:11] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:50:11] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:50:11] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:50:11] Explicit valence for atom # 10 C, 5, is greater than permitted

[1025/2737] (1935s elapsed, ~54 min left)

[17:50:45] Explicit valence for atom # 40 N, 4, is greater than permitted
[17:50:45] Explicit valence for atom # 40 N, 4, is greater than permitted
[17:50:45] Explicit valence for atom # 40 N, 4, is greater than permitted
[17:50:45] Explicit valence for atom # 40 N, 4, is greater than permitted
[17:50:47] Explicit valence for atom # 40 N, 4, is greater than permitted
[17:50:47] Explicit valence for atom # 40 N, 4, is greater than permitted
[17:50:47] Explicit valence for atom # 40 N, 4, is greater than permitted
[17:50:47] Explicit valence for atom # 40 N, 4, is greater than permitted
[17:50:48] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:50:48] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:50:50] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:50:50] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:50:52] Explicit valence for atom # 8 C, 5, is greater than permitted
[17:50:52] Explicit valence for atom # 8 C, 5, is greater than permitted
[17:50:52] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:50:52] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:50:58] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:50:58] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:51:06] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:51:06] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:51:06] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:51:06] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:51:06] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:51:06] Explicit valence for atom # 19 C, 5, is greater than permitted

[1050/2737] (1971s elapsed, ~53 min left)

[17:51:07] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:51:07] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:51:07] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:51:07] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:51:07] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:51:07] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:51:09] Explicit valence for atom # 38 N, 4, is greater than permitted
[17:51:09] Explicit valence for atom # 38 N, 4, is greater than permitted
[17:51:09] Explicit valence for atom # 38 N, 4, is greater than permitted
[17:51:09] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:51:09] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:51:09] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:51:09] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:51:10] Explicit valence for atom # 38 N, 4, is greater than permitted
[17:51:10] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:51:10] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:51:10] Explicit valence for atom # 38 N, 4, is greater than permitted
[17:51:10] Explicit valence for atom # 38 N, 4, is greater than permitted
[17:51:10] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:51:10] Explicit valence for atom # 3 C, 5, is greater than permitted
[17:51:12] Explicit valence for atom # 23 N, 4, is greater than permitted
[17:51:12] Explicit valence for atom # 23 N, 4, is greater than permitted
[17:51:12] Explicit valence for atom # 23 N, 4, is greater than permitted
[17:51:12] Explicit valence for atom # 23 N, 4, is greater than permitted
[17:51:14] Explicit valence for atom # 23 N, 4, is greater than permitted
[17:51:14] Explicit valence for atom # 23 N, 4, is greater than permitted
[17:51:14] Explicit valence for atom # 23 N, 4, is greater than permitted
[17:51:14] Explicit valence for atom # 23 N, 4, is greater than permitted
[17:51:25] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:51:25] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:51:25] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:51:25] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:51:25] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:51:25] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:51:25] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:51:25] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:51:25] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:51:25] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:51:25] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:51:25] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:51:25] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:51:25] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:51:25] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:51:25] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:51:28] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:51:28] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:51:28] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:51:28] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:51:38] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:51:38] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:51:38] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:51:38] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:51:40] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:51:40] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:51:40] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:51:40] Explicit valence for atom # 19 C, 5, is greater than permitted

[1075/2737] (2009s elapsed, ~52 min left)

[17:51:45] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:51:45] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:51:45] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:51:45] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:51:50] Explicit valence for atom # 4 C, 5, is greater than permitted
[17:51:50] Explicit valence for atom # 4 C, 5, is greater than permitted
[17:51:51] Explicit valence for atom # 4 C, 5, is greater than permitted
[17:51:51] Explicit valence for atom # 4 C, 5, is greater than permitted
[17:51:53] Explicit valence for atom # 24 N, 4, is greater than permitted
[17:51:53] Explicit valence for atom # 24 N, 4, is greater than permitted
[17:52:09] Explicit valence for atom # 7 C, 6, is greater than permitted
[17:52:09] Explicit valence for atom # 7 C, 6, is greater than permitted
[17:52:09] Explicit valence for atom # 7 C, 6, is greater than permitted
[17:52:09] Explicit valence for atom # 7 C, 6, is greater than permitted

[1100/2737] (2049s elapsed, ~51 min left)
[1125/2737] (2092s elapsed, ~50 min left)

[17:53:10] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:53:10] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:53:10] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:53:10] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:53:10] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:53:10] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:53:10] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:53:10] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:53:12] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:53:12] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:53:12] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:53:12] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:53:12] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:53:12] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:53:12] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:53:12] Explicit valence for atom # 10 C, 5, is greater than permitted
[17:53:21] Explicit valence for atom # 9 N, 4, is greater than permitted
[17:53:21] Explicit valence for atom # 9 N, 4, is greater than permitted
[17:53:21] Explicit valence for atom # 9 N, 4, is greater than permitted
[17:53:21] Explicit valence for atom # 9 N, 4, is greater than permitted
[17:53:21] Explicit valence for atom # 9 N, 4, is greater than permitted
[17:53:21] Explicit valence for atom # 9 N, 4, is greater than permitted
[17:53:21] Explicit valence for atom # 9 N, 4, is greater than permitted
[17:53:21] Explicit valence for atom # 9 N, 4, is greater than permitted
[17:53:22] Explicit valence for atom # 9 N, 4, is greater than permitted
[17:53:22] Explicit valence for atom # 9 N, 4, is greater than permitted
[17:53:22] Explicit valence for atom # 9 N, 4, is greater than permitted
[17:53:22] Explicit valence for atom # 9 N, 4, is greater than permitted
[17:53:22] Explicit valence for atom # 9 N, 4, is greater than permitted
[17:53:22] Explicit valence for atom # 9 N, 4, is greater than permitted
[17:53:22] Explicit valence for atom # 9 N, 4, is greater than permitted
[17:53:22] Explicit valence for atom # 9 N, 4, is greater than permitted
[17:53:23] Explicit valence for atom # 8 N, 4, is greater than permitted
[17:53:23] Explicit valence for atom # 8 N, 4, is greater than permitted
[17:53:23] Explicit valence for atom # 8 N, 4, is greater than permitted
[17:53:23] Explicit valence for atom # 8 N, 4, is greater than permitted
[17:53:24] Explicit valence for atom # 8 N, 4, is greater than permitted
[17:53:24] Explicit valence for atom # 8 N, 4, is greater than permitted
[17:53:24] Explicit valence for atom # 8 N, 4, is greater than permitted
[17:53:24] Explicit valence for atom # 8 N, 4, is greater than permitted
[17:53:28] Explicit valence for atom # 1 C, 6, is greater than permitted
[17:53:28] Explicit valence for atom # 1 C, 6, is greater than permitted
[17:53:28] Explicit valence for atom # 1 C, 6, is greater than permitted
[17:53:28] Explicit valence for atom # 1 C, 6, is greater than permitted
[17:53:30] Explicit valence for atom # 1 C, 6, is greater than permitted
[17:53:30] Explicit valence for atom # 1 C, 6, is greater than permitted
[17:53:30] Explicit valence for atom # 1 C, 6, is greater than permitted
[17:53:30] Explicit valence for atom # 1 C, 6, is greater than permitted

[1150/2737] (2129s elapsed, ~49 min left)
[1175/2737] (2171s elapsed, ~48 min left)

[17:54:29] Explicit valence for atom # 2 C, 5, is greater than permitted
[17:54:29] Explicit valence for atom # 2 C, 5, is greater than permitted
[17:54:29] Explicit valence for atom # 2 C, 5, is greater than permitted
[17:54:29] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:54:29] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:54:29] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:54:29] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:54:29] Explicit valence for atom # 16 C, 5, is greater than permitted
[17:54:29] Explicit valence for atom # 16 C, 5, is greater than permitted
[17:54:29] Explicit valence for atom # 16 C, 5, is greater than permitted
[17:54:29] Explicit valence for atom # 16 C, 5, is greater than permitted
[17:54:29] Explicit valence for atom # 2 C, 5, is greater than permitted
[17:54:29] Explicit valence for atom # 2 C, 5, is greater than permitted
[17:54:29] Explicit valence for atom # 2 C, 5, is greater than permitted
[17:54:29] Explicit valence for atom # 2 C, 5, is greater than permitted
[17:54:29] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:54:29] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:54:29] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:54:29] Explicit valence for atom # 17 C, 5, is greater than permitted
[17:54:29] Explicit valence for atom # 16 C, 5, is greater than permitted
[17:54:29] Explicit valence for atom # 16 C, 5, is greater than permitted
[17:54:29] Explicit valence for atom # 16 C, 5, is greater than permitted
[17:54:29] Explicit valence for atom # 16 C, 5, is greater than permitted
[17:54:29] Explicit valence for atom # 2 C, 5, is greater than permitted
[17:54:58] Explicit valence for atom # 17 O, 3, is greater than permitted
[17:54:58] Explicit valence for atom # 17 O, 3, is greater than permitted
[17:54:58] Explicit valence for atom # 17 O, 3, is greater than permitted
[17:54:58] Explicit valence for atom # 17 O, 3, is greater than permitted

[1200/2737] (2203s elapsed, ~47 min left)

[17:54:58] Explicit valence for atom # 17 O, 3, is greater than permitted
[17:54:58] Explicit valence for atom # 17 O, 3, is greater than permitted
[17:54:58] Explicit valence for atom # 17 O, 3, is greater than permitted
[17:54:58] Explicit valence for atom # 17 O, 3, is greater than permitted
[17:54:59] Explicit valence for atom # 13 O, 3, is greater than permitted
[17:54:59] Explicit valence for atom # 13 O, 3, is greater than permitted
[17:54:59] Explicit valence for atom # 13 O, 3, is greater than permitted
[17:54:59] Explicit valence for atom # 13 O, 3, is greater than permitted
[17:55:00] Explicit valence for atom # 13 O, 3, is greater than permitted
[17:55:00] Explicit valence for atom # 13 O, 3, is greater than permitted
[17:55:00] Explicit valence for atom # 13 O, 3, is greater than permitted
[17:55:00] Explicit valence for atom # 13 O, 3, is greater than permitted
[17:55:01] Explicit valence for atom # 13 O, 3, is greater than permitted
[17:55:01] Explicit valence for atom # 13 O, 3, is greater than permitted
[17:55:01] Explicit valence for atom # 13 O, 3, is greater than permitted
[17:55:01] Explicit valence for atom # 13 O, 3, is greater than permitted
[17:55:01] Explicit valence for atom # 13 O, 3, is greater than permitted
[17:55:01] Explicit valence for atom # 13 O, 3, is greater than permitted
[17:55:01] Explicit valence for atom # 13 O, 3, is greater than permitted
[17:55:01] Explicit valence for atom # 13 O, 3, is greater than permitted

[1225/2737] (2246s elapsed, ~46 min left)

[17:56:01] Explicit valence for atom # 17 O, 3, is greater than permitted
[17:56:01] Explicit valence for atom # 17 O, 2, is greater than permitted
[17:56:01] Explicit valence for atom # 17 O, 2, is greater than permitted
[17:56:01] Explicit valence for atom # 20 O, 2, is greater than permitted
[17:56:01] Explicit valence for atom # 20 O, 2, is greater than permitted
[17:56:01] Explicit valence for atom # 20 O, 2, is greater than permitted
[17:56:02] Explicit valence for atom # 17 O, 3, is greater than permitted
[17:56:02] Explicit valence for atom # 17 O, 2, is greater than permitted
[17:56:02] Explicit valence for atom # 17 O, 2, is greater than permitted
[17:56:02] Explicit valence for atom # 20 O, 2, is greater than permitted
[17:56:02] Explicit valence for atom # 20 O, 2, is greater than permitted
[17:56:02] Explicit valence for atom # 20 O, 2, is greater than permitted

[1250/2737] (2282s elapsed, ~45 min left)

[17:56:34] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:56:34] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:56:34] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:56:34] Explicit valence for atom # 11 C, 5, is greater than permitted
[17:56:54] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:56:54] Explicit valence for atom # 7 C, 5, is greater than permitted

[1275/2737] (2320s elapsed, ~44 min left)

[17:56:58] Explicit valence for atom # 27 C, 6, is greater than permitted
[17:56:58] Explicit valence for atom # 27 C, 6, is greater than permitted
[17:56:58] Explicit valence for atom # 27 C, 6, is greater than permitted
[17:56:58] Explicit valence for atom # 27 C, 6, is greater than permitted
[17:57:00] Explicit valence for atom # 18 C, 5, is greater than permitted
[17:57:01] Explicit valence for atom # 18 C, 5, is greater than permitted
[17:57:28] Explicit valence for atom # 14 C, 5, is greater than permitted
[17:57:28] Explicit valence for atom # 14 C, 5, is greater than permitted
[17:57:28] Explicit valence for atom # 14 C, 5, is greater than permitted
[17:57:28] Explicit valence for atom # 14 C, 5, is greater than permitted
[17:57:29] Explicit valence for atom # 14 C, 5, is greater than permitted
[17:57:29] Explicit valence for atom # 14 C, 5, is greater than permitted
[17:57:29] Explicit valence for atom # 14 C, 5, is greater than permitted
[17:57:29] Explicit valence for atom # 14 C, 5, is greater than permitted
[17:57:31] Explicit valence for atom # 14 C, 5, is greater than permitted
[17:57:31] Explicit valence for atom # 14 C, 5, is greater than permitted
[17:57:31] Explicit valence for atom # 14 C, 5, is greater than permitted
[17:57:31] Explicit valence for atom # 14 C, 5, is greater than permitted
[17:57:32] Explicit valence for atom # 14 C, 5, is greater than permitted
[17:57:32] Explicit valence for atom # 14 C, 5, is greater than permitted
[17:57:32] Explicit valence for atom # 14 C, 5, is greater than permitted
[17:57:32] Explicit valence for atom # 14 C, 5, is greater than permitted

[1300/2737] (2364s elapsed, ~44 min left)

[17:57:44] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:57:44] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:57:44] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:57:44] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:57:44] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:57:44] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:58:12] Explicit valence for atom # 14 N, 4, is greater than permitted
[17:58:12] Explicit valence for atom # 14 N, 4, is greater than permitted
[17:58:12] Explicit valence for atom # 14 N, 4, is greater than permitted
[17:58:12] Explicit valence for atom # 14 N, 4, is greater than permitted
[17:58:13] Explicit valence for atom # 14 N, 4, is greater than permitted
[17:58:13] Explicit valence for atom # 14 N, 4, is greater than permitted
[17:58:13] Explicit valence for atom # 14 N, 4, is greater than permitted
[17:58:13] Explicit valence for atom # 14 N, 4, is greater than permitted

[1325/2737] (2399s elapsed, ~43 min left)

[17:58:31] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:58:31] Explicit valence for atom # 9 C, 5, is greater than permitted
[17:58:32] Explicit valence for atom # 32 C, 5, is greater than permitted
[17:58:32] Explicit valence for atom # 33 C, 5, is greater than permitted
[17:58:32] Explicit valence for atom # 20 C, 5, is greater than permitted
[17:58:32] Explicit valence for atom # 33 C, 5, is greater than permitted
[17:58:34] Explicit valence for atom # 32 C, 5, is greater than permitted
[17:58:34] Explicit valence for atom # 33 C, 5, is greater than permitted
[17:58:34] Explicit valence for atom # 20 C, 5, is greater than permitted
[17:58:34] Explicit valence for atom # 33 C, 5, is greater than permitted
[17:58:39] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:58:39] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:58:39] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:58:39] Explicit valence for atom # 7 C, 5, is greater than permitted
[17:58:41] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:58:41] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:58:42] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:58:42] Explicit valence for atom # 19 C, 5, is greater than permitted
[17:58:47] Explicit valence for atom # 12 C, 5, is greater than permitted
[17:58:47] Explicit valence for atom # 12 C, 5, is greater than permitted

[1350/2737] (2435s elapsed, ~42 min left)

[17:59:11] Explicit valence for atom # 6 C, 5, is greater than permitted
[17:59:11] Explicit valence for atom # 6 C, 5, is greater than permitted
[17:59:12] Explicit valence for atom # 6 C, 5, is greater than permitted
[17:59:12] Explicit valence for atom # 6 C, 5, is greater than permitted

[1375/2737] (2470s elapsed, ~41 min left)

[17:59:48] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:59:48] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:59:48] Explicit valence for atom # 0 N, 4, is greater than permitted
[17:59:48] Explicit valence for atom # 0 N, 4, is greater than permitted

[1400/2737] (2504s elapsed, ~40 min left)

[17:59:59] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:00:22] Explicit valence for atom # 9 N, 4, is greater than permitted
[18:00:22] Explicit valence for atom # 9 N, 4, is greater than permitted
[18:00:22] Explicit valence for atom # 9 N, 4, is greater than permitted
[18:00:22] Explicit valence for atom # 9 N, 4, is greater than permitted
[18:00:23] Explicit valence for atom # 9 N, 4, is greater than permitted
[18:00:23] Explicit valence for atom # 9 N, 4, is greater than permitted
[18:00:23] Explicit valence for atom # 9 N, 4, is greater than permitted
[18:00:23] Explicit valence for atom # 9 N, 4, is greater than permitted
[18:00:33] Explicit valence for atom # 11 N, 5, is greater than permitted
[18:00:33] Explicit valence for atom # 11 N, 5, is greater than permitted
[18:00:34] Explicit valence for atom # 11 N, 5, is greater than permitted
[18:00:34] Explicit valence for atom # 11 N, 5, is greater than permitted
[18:00:36] Explicit valence for atom # 12 N, 4, is greater than permitted
[18:00:36] Explicit valence for atom # 12 N, 4, is greater than permitted
[18:00:36] Explicit valence for atom # 12 N, 4, is greater than permitted
[18:00:36] Explicit valence for atom # 12 N, 4, is greater than permitted
[18:00:36] Explicit valence for atom # 12 N, 4, is greater than permitted
[18:00:36] Explicit valence for atom # 12 N, 4, is greater than permitted
[18:00:36] Explicit valence for atom # 12 N, 4, is greater than permitted
[18:00:36] Explicit valence for atom # 12 N, 4, is greater than permitted
[18:00:39] Explicit valence for atom # 12 N, 4, is greater than permitted
[18:00:39] Explicit valence for atom # 12 N, 4, is greater than permitted
[18:00:39] Explicit valence for atom # 12 N, 4, is greater than permitted
[18:00:39] Explicit valence for atom # 12 N, 4, is greater than permitted
[18:00:39] Explicit valence for atom # 12 N, 4, is greater than permitted
[18:00:39] Explicit valence for atom # 12 N, 4, is greater than permitted
[18:00:39] Explicit valence for atom # 12 N, 4, is greater than permitted
[18:00:39] Explicit valence for atom # 12 N, 4, is greater than permitted

[1425/2737] (2545s elapsed, ~39 min left)

[18:00:52] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:00:52] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:00:52] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:00:52] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:00:53] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:00:53] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:00:53] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:00:53] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:01:00] Explicit valence for atom # 10 N, 4, is greater than permitted
[18:01:00] Explicit valence for atom # 10 N, 4, is greater than permitted
[18:01:00] Explicit valence for atom # 10 N, 4, is greater than permitted
[18:01:00] Explicit valence for atom # 10 N, 4, is greater than permitted
[18:01:02] Explicit valence for atom # 15 N, 4, is greater than permitted
[18:01:02] Explicit valence for atom # 15 N, 4, is greater than permitted
[18:01:02] Explicit valence for atom # 15 N, 4, is greater than permitted
[18:01:02] Explicit valence for atom # 15 N, 4, is greater than permitted
[18:01:03] Explicit valence for atom # 15 N, 4, is greater than permitted
[18:01:03] Explicit valence for atom # 15 N, 4, is greater than permitted
[18:01:03] Explicit valence for atom # 15 N, 4, is greater than permitted
[18:01:03] Explicit valence for atom # 15 N, 4, is greater than permitted
[18:01:05] Explicit valence for atom # 4 C, 5, is greater than permitted
[18:01:05] Explicit valence for atom # 4 C, 5, is greater than permitted
[18:01:05] Explicit valence for atom # 4 C, 5, is greater than permitted
[18:01:06] Explicit valence for atom # 4 C, 5, is greater than permitted
[18:01:06] Explicit valence for atom # 4 C, 5, is greater than permitted
[18:01:06] Explicit valence for atom # 4 C, 5, is greater than permitted

[1450/2737] (2584s elapsed, ~38 min left)
[1475/2737] (2638s elapsed, ~38 min left)
[1500/2737] (2670s elapsed, ~37 min left)

[18:02:54] Explicit valence for atom # 16 C, 5, is greater than permitted
[18:02:54] Explicit valence for atom # 16 C, 5, is greater than permitted
[18:02:54] Explicit valence for atom # 16 C, 5, is greater than permitted
[18:02:54] Explicit valence for atom # 16 C, 5, is greater than permitted
[18:02:56] Explicit valence for atom # 16 C, 5, is greater than permitted
[18:02:56] Explicit valence for atom # 16 C, 5, is greater than permitted
[18:02:56] Explicit valence for atom # 16 C, 5, is greater than permitted
[18:02:56] Explicit valence for atom # 16 C, 5, is greater than permitted
[18:03:06] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:03:06] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:03:06] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:03:06] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:03:19] Explicit valence for atom # 5 C, 5, is greater than permitted
[18:03:19] Explicit valence for atom # 5 C, 5, is greater than permitted
[18:03:19] Explicit valence for atom # 5 C, 5, is greater than permitted
[18:03:19] Explicit valence for atom # 5 C, 5, is greater than permitted
[18:03:19] Explicit valence for atom # 5 C, 5, is greater than permitted
[18:03:19] Explicit valence for atom # 5 C, 5, is greater than permitted
[18:03:19] Explicit valence for atom # 5 C, 5, is greater than permitted
[18:03:19] Explicit valence for atom # 5 C, 5, is greater than permitted
[18:03:19] Explicit valence for atom # 5 C, 5, is greater than permitted
[18:03:19] Explicit valence for atom # 5 C, 5, is greater than permitted
[18:03:19] Explicit valence for atom # 5 C, 5, is greater than permitted
[18:03:19] Explicit valence for atom # 5 C, 5, is greater than permitted

[1525/2737] (2707s elapsed, ~36 min left)

[18:03:23] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:03:23] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:03:23] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:03:23] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:03:30] Explicit valence for atom # 36 C, 5, is greater than permitted
[18:03:31] Explicit valence for atom # 36 C, 5, is greater than permitted

[1550/2737] (2743s elapsed, ~35 min left)

[18:04:01] Explicit valence for atom # 60 C, 5, is greater than permitted
[18:04:01] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:01] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:01] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:01] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:01] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:01] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:01] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:01] Explicit valence for atom # 60 C, 5, is greater than permitted
[18:04:01] Explicit valence for atom # 60 C, 5, is greater than permitted
[18:04:01] Explicit valence for atom # 60 C, 5, is greater than permitted
[18:04:01] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:01] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:01] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:01] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:01] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:01] Explicit valence for atom # 60 C, 5, is greater than permitted
[18:04:01] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:01] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:01] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:01] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:01] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:01] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:01] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:01] Explicit valence for atom # 60 C, 5, is greater than permitted
[18:04:01] Explicit valence for atom # 60 C, 5, is greater than permitted
[18:04:01] Explicit valence for atom # 60 C, 5, is greater than permitted
[18:04:01] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:01] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:01] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:01] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:01] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:02] Explicit valence for atom # 59 C, 5, is greater than permitted
[18:04:02] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:02] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:02] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:02] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:02] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:02] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:02] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:02] Explicit valence for atom # 59 C, 5, is greater than permitted
[18:04:02] Explicit valence for atom # 59 C, 5, is greater than permitted
[18:04:02] Explicit valence for atom # 59 C, 5, is greater than permitted
[18:04:02] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:02] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:02] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:02] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:02] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:03] Explicit valence for atom # 59 C, 5, is greater than permitted
[18:04:03] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:03] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:03] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:03] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:03] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:03] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:03] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:03] Explicit valence for atom # 59 C, 5, is greater than permitted
[18:04:03] Explicit valence for atom # 59 C, 5, is greater than permitted
[18:04:03] Explicit valence for atom # 59 C, 5, is greater than permitted
[18:04:03] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:03] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:03] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:03] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:03] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:04] Explicit valence for atom # 61 C, 5, is greater than permitted
[18:04:04] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:04] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:04] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:04] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:04] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:04] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:04] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:04] Explicit valence for atom # 61 C, 5, is greater than permitted
[18:04:04] Explicit valence for atom # 61 C, 5, is greater than permitted
[18:04:04] Explicit valence for atom # 61 C, 5, is greater than permitted
[18:04:04] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:04] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:04] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:04] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:04] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:05] Explicit valence for atom # 61 C, 5, is greater than permitted
[18:04:05] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:05] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:05] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:05] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:05] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:05] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:05] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:05] Explicit valence for atom # 61 C, 5, is greater than permitted
[18:04:05] Explicit valence for atom # 61 C, 5, is greater than permitted
[18:04:05] Explicit valence for atom # 61 C, 5, is greater than permitted
[18:04:05] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:05] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:05] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:05] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:05] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:04:09] Explicit valence for atom # 10 N, 4, is greater than permitted
[18:04:09] Explicit valence for atom # 10 N, 4, is greater than permitted
[18:04:09] Explicit valence for atom # 10 N, 4, is greater than permitted
[18:04:09] Explicit valence for atom # 7 C, 6, is greater than permitted
[18:04:09] Explicit valence for atom # 7 C, 6, is greater than permitted
[18:04:09] Explicit valence for atom # 7 C, 6, is greater than permitted
[18:04:09] Explicit valence for atom # 7 C, 6, is greater than permitted
[18:04:09] Explicit valence for atom # 10 N, 4, is greater than permitted
[18:04:09] Explicit valence for atom # 10 N, 4, is greater than permitted
[18:04:09] Explicit valence for atom # 10 N, 4, is greater than permitted
[18:04:09] Explicit valence for atom # 10 N, 4, is greater than permitted
[18:04:09] Explicit valence for atom # 7 C, 6, is greater than permitted
[18:04:09] Explicit valence for atom # 7 C, 6, is greater than permitted
[18:04:09] Explicit valence for atom # 7 C, 6, is greater than permitted
[18:04:09] Explicit valence for atom # 7 C, 6, is greater than permitted
[18:04:09] Explicit valence for atom # 10 N, 4, is greater than permitted

[1575/2737] (2781s elapsed, ~34 min left)
[1600/2737] (2820s elapsed, ~33 min left)

[18:05:23] Explicit valence for atom # 14 N, 4, is greater than permitted
[18:05:23] Explicit valence for atom # 14 N, 4, is greater than permitted

[1625/2737] (2857s elapsed, ~33 min left)
[1650/2737] (2898s elapsed, ~32 min left)

[18:07:14] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:07:14] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:07:14] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:07:14] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:07:14] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:07:14] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:07:14] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:07:15] Explicit valence for atom # 7 C, 5, is greater than permitted

[1675/2737] (2944s elapsed, ~31 min left)

[18:07:39] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:07:39] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:07:39] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:07:39] Explicit valence for atom # 7 C, 5, is greater than permitted

[1700/2737] (2981s elapsed, ~30 min left)

[18:07:56] Explicit valence for atom # 9 C, 5, is greater than permitted
[18:07:56] Explicit valence for atom # 9 C, 5, is greater than permitted
[18:08:02] Explicit valence for atom # 9 C, 5, is greater than permitted
[18:08:02] Explicit valence for atom # 9 C, 5, is greater than permitted
[18:08:02] Explicit valence for atom # 9 C, 5, is greater than permitted
[18:08:02] Explicit valence for atom # 9 C, 5, is greater than permitted
[18:08:29] Explicit valence for atom # 13 C, 5, is greater than permitted
[18:08:29] Explicit valence for atom # 13 C, 5, is greater than permitted
[18:08:29] Explicit valence for atom # 13 C, 5, is greater than permitted
[18:08:29] Explicit valence for atom # 13 C, 5, is greater than permitted
[18:08:54] Explicit valence for atom # 56 C, 5, is greater than permitted
[18:08:54] Explicit valence for atom # 56 C, 5, is greater than permitted
[18:08:54] Explicit valence for atom # 56 C, 5, is greater than permitted
[18:08:54] Explicit valence for atom # 56 C, 5, is greater than permitted
[18:08:55] Explicit valence for atom # 56 C, 5, is greater than permitted
[18:08:55] Explicit valence for atom # 56 C, 5, is greater than permitted
[18:08:59] Explicit valence for atom # 56 C, 5, is greater than permitted
[18:08:59] Explicit valence for atom # 56 C, 5, is greater than permitted
[18:08:59] Explicit valence for atom # 56 C, 5, is greater than permitted
[18:08:59] Explicit valence for atom # 56 C, 5, is greater than permitted
[18:08:59] Explicit valence for atom # 56 C, 5, is greater than permitted
[18:08:59] Explicit valence for atom # 56 C, 5, is greater than permitted

[1725/2737] (3046s elapsed, ~30 min left)

[18:09:05] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:09:05] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:09:05] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:09:05] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:09:05] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:09:05] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:09:08] Explicit valence for atom # 18 C, 5, is greater than permitted
[18:09:08] Explicit valence for atom # 18 C, 5, is greater than permitted
[18:09:08] Explicit valence for atom # 18 C, 5, is greater than permitted
[18:09:08] Explicit valence for atom # 18 C, 5, is greater than permitted

[1750/2737] (3085s elapsed, ~29 min left)

[18:10:01] Explicit valence for atom # 9 N, 4, is greater than permitted
[18:10:01] Explicit valence for atom # 9 N, 4, is greater than permitted
[18:10:01] Explicit valence for atom # 31 N, 4, is greater than permitted
[18:10:01] Explicit valence for atom # 31 N, 4, is greater than permitted
[18:10:01] Explicit valence for atom # 1 C, 6, is greater than permitted
[18:10:01] Explicit valence for atom # 1 C, 6, is greater than permitted
[18:10:03] Explicit valence for atom # 9 N, 4, is greater than permitted
[18:10:03] Explicit valence for atom # 9 N, 4, is greater than permitted
[18:10:03] Explicit valence for atom # 31 N, 4, is greater than permitted
[18:10:03] Explicit valence for atom # 31 N, 4, is greater than permitted
[18:10:03] Explicit valence for atom # 1 C, 6, is greater than permitted
[18:10:03] Explicit valence for atom # 1 C, 6, is greater than permitted
[18:10:08] Explicit valence for atom # 3 C, 5, is greater than permitted
[18:10:08] Explicit valence for atom # 3 C, 5, is greater than permitted
[18:10:08] Explicit valence for atom # 3 C, 5, is greater than permitted
[18:10:08] Explicit valence for atom # 3 C, 5, is greater than permitted
[18:10:09] Explicit valence for atom # 3 C, 5, is greater than permitted
[18:10:09] Explicit valence for atom # 3 C, 5, is greater than permitted
[18:10:09] Explicit valence for atom # 3 C, 5, is greater than permitted
[18:10:09] Explicit valence for atom # 3 C, 5, is greater than permitted
[18:10:12] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:10:12] Explicit valence for atom # 6 C, 5, is greater than permitted

[1775/2737] (3118s elapsed, ~28 min left)

[18:10:13] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:10:13] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:10:13] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:10:13] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:10:13] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:10:13] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:10:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:10:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:10:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:10:17] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:10:37] Explicit valence for atom # 8 C, 5, is greater than permitted
[18:10:37] Explicit valence for atom # 8 C, 5, is greater than permitted
[18:10:42] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:10:42] Explicit valence for atom # 7 C, 5, is greater than permitted

[1800/2737] (3149s elapsed, ~27 min left)

[18:10:44] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:10:44] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:10:46] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:10:46] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:10:48] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:10:48] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:11:14] Explicit valence for atom # 31 N, 5, is greater than permitted
[18:11:14] Explicit valence for atom # 31 N, 5, is greater than permitted
[18:11:15] Explicit valence for atom # 31 N, 5, is greater than permitted
[18:11:15] Explicit valence for atom # 31 N, 5, is greater than permitted

[1825/2737] (3181s elapsed, ~26 min left)

[18:11:16] Explicit valence for atom # 31 N, 5, is greater than permitted
[18:11:16] Explicit valence for atom # 31 N, 5, is greater than permitted
[18:11:16] Explicit valence for atom # 31 N, 5, is greater than permitted
[18:11:16] Explicit valence for atom # 31 N, 5, is greater than permitted
[18:11:49] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:11:49] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:11:49] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:11:49] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:11:49] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:11:49] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:11:49] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:11:49] Explicit valence for atom # 7 C, 5, is greater than permitted

[1850/2737] (3220s elapsed, ~26 min left)
[1875/2737] (3258s elapsed, ~25 min left)

[18:12:48] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:12:48] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:12:54] Explicit valence for atom # 9 C, 5, is greater than permitted
[18:12:54] Explicit valence for atom # 9 C, 5, is greater than permitted
[18:12:54] Explicit valence for atom # 13 N, 4, is greater than permitted
[18:12:54] Explicit valence for atom # 13 N, 4, is greater than permitted
[18:13:00] Explicit valence for atom # 10 C, 5, is greater than permitted
[18:13:00] Explicit valence for atom # 10 C, 5, is greater than permitted
[18:13:00] Explicit valence for atom # 10 C, 5, is greater than permitted
[18:13:00] Explicit valence for atom # 10 C, 5, is greater than permitted
[18:13:00] Explicit valence for atom # 10 C, 5, is greater than permitted
[18:13:00] Explicit valence for atom # 10 C, 5, is greater than permitted
[18:13:00] Explicit valence for atom # 10 C, 5, is greater than permitted
[18:13:00] Explicit valence for atom # 10 C, 5, is greater than permitted
[18:13:00] Explicit valence for atom # 10 C, 5, is greater than permitted
[18:13:00] Explicit valence for atom # 10 C, 5, is greater than permitted
[18:13:00] Explicit valence for atom # 10 C, 5, is greater than permitted
[18:13:00] Explicit valence for atom # 10 C, 5, is greater than permitted
[18:13:04] Explicit valence for atom # 9 C, 5, is greater than permitted
[18:13:04] Explicit valence for atom # 9 C, 5, is greater than permitted

[1900/2737] (3295s elapsed, ~24 min left)

[18:13:13] Explicit valence for atom # 27 C, 5, is greater than permitted
[18:13:13] Explicit valence for atom # 27 C, 5, is greater than permitted
[18:13:15] Explicit valence for atom # 27 C, 5, is greater than permitted
[18:13:15] Explicit valence for atom # 27 C, 5, is greater than permitted
[18:13:18] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:13:18] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:13:18] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:13:18] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:13:18] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:13:18] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:13:18] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:13:18] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:13:22] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:13:22] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:13:22] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:13:22] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:13:22] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:13:22] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:13:22] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:13:22] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:13:24] Explicit valence for atom # 32 C, 5, is greater than permitted
[18:13:24] Explicit valence for atom # 32 C, 5, is greater than permitted
[18:13:24] Explicit valence for atom # 32 C, 5, is greater than permitted
[18:13:24] Explicit valence for atom # 32 C, 5, is greater than permitted
[18:13:25] Explicit valence for atom # 32 C, 5, is greater than permitted
[18:13:25] Explicit valence for atom # 32 C, 5, is greater than permitted
[18:13:25] Explicit valence for atom # 32 C, 5, is greater than permitted
[18:13:25] Explicit valence for atom # 32 C, 5, is greater than permitted
[18:13:27] Explicit valence for atom # 32 C, 5, is greater than permitted
[18:13:27] Explicit valence for atom # 32 C, 5, is greater than permitted
[18:13:27] Explicit valence for atom # 32 C, 5, is greater than permitted
[18:13:27] Explicit valence for atom # 32 C, 5, is greater than permitted
[18:13:28] Explicit valence for atom # 32 C, 5, is greater than permitted
[18:13:28] Explicit valence for atom # 32 C, 5, is greater than permitted
[18:13:28] Explicit valence for atom # 32 C, 5, is greater than permitted
[18:13:28] Explicit valence for atom # 32 C, 5, is greater than permitted
[18:13:30] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:30] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:30] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:30] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:30] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:30] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:30] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:30] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:30] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:30] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:30] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:30] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:30] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:30] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:30] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:30] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:31] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:31] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:31] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:31] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:31] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:31] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:31] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:31] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:31] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:31] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:31] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:31] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:31] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:31] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:31] Explicit valence for atom # 19 C, 5, is greater than permitted
[18:13:31] Explicit valence for atom # 19 C, 5, is greater than permitted

[1925/2737] (3338s elapsed, ~23 min left)

[18:14:26] Explicit valence for atom # 35 C, 5, is greater than permitted
[18:14:26] Explicit valence for atom # 35 C, 5, is greater than permitted
[18:14:26] Explicit valence for atom # 35 C, 5, is greater than permitted
[18:14:26] Explicit valence for atom # 35 C, 5, is greater than permitted
[18:14:27] Explicit valence for atom # 22 C, 6, is greater than permitted
[18:14:27] Explicit valence for atom # 22 C, 6, is greater than permitted
[18:14:29] Explicit valence for atom # 22 C, 6, is greater than permitted
[18:14:29] Explicit valence for atom # 22 C, 6, is greater than permitted
[18:14:32] Explicit valence for atom # 11 C, 5, is greater than permitted
[18:14:32] Explicit valence for atom # 11 C, 5, is greater than permitted
[18:14:32] Explicit valence for atom # 11 C, 5, is greater than permitted
[18:14:32] Explicit valence for atom # 11 C, 5, is greater than permitted
[18:14:32] Explicit valence for atom # 11 C, 5, is greater than permitted
[18:14:32] Explicit valence for atom # 11 C, 5, is greater than permitted
[18:14:32] Explicit valence for atom # 11 C, 5, is greater than permitted
[18:14:32] Explicit valence for atom # 11 C, 5, is greater than permitted

[1950/2737] (3379s elapsed, ~23 min left)

[18:14:42] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:14:42] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:14:42] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:14:42] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:14:42] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:14:42] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:14:42] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:14:42] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:14:50] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:14:50] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:14:50] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:14:50] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:14:52] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:14:52] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:14:52] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:14:52] Explicit valence for atom # 0 N, 4, is greater than permitted

[1975/2737] (3416s elapsed, ~22 min left)

[18:15:33] Explicit valence for atom # 2 H, 2, is greater than permitted
[18:15:33] Explicit valence for atom # 2 H, 2, is greater than permitted
[18:15:33] Explicit valence for atom # 2 H, 2, is greater than permitted
[18:15:33] Explicit valence for atom # 2 H, 2, is greater than permitted
[18:15:34] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:15:34] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:15:34] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:15:34] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:15:34] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:15:34] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:15:34] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:15:34] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:15:34] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:15:34] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:15:34] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:15:34] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:15:35] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:15:35] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:15:35] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:15:35] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:15:35] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:15:35] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:15:35] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:15:35] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:15:35] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:15:35] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:15:35] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:15:35] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:15:39] Explicit valence for atom # 9 N, 4, is greater than permitted
[18:15:39] Explicit valence for atom # 9 N, 4, is greater than permitted
[18:15:39] Explicit valence for atom # 9 N, 4, is greater than permitted
[18:15:39] Explicit valence for atom # 9 N, 4, is greater than permitted
[18:15:39] Explicit valence for atom # 9 N, 4, is greater than permitted
[18:15:39] Explicit valence for atom # 9 N, 4, is greater than permitted
[18:15:41] Explicit valence for atom # 9 N, 4, is greater than permitted
[18:15:41] Explicit valence for atom # 9 N, 4, is greater than permitted
[18:15:41] Explicit valence for atom # 9 N, 4, is greater than permitted
[18:15:41] Explicit valence for atom # 9 N, 4, is greater than permitted
[18:15:41] Explicit valence for atom # 9 N, 4, is greater than permitted
[18:15:41] Explicit valence for atom # 9 N, 4, is greater than permitted
[18:15:43] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:15:43] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:15:43] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:15:43] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:15:43] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:15:43] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:15:43] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:15:43] Explicit valence for atom # 7 C, 5, is greater than permitted

[2000/2737] (3454s elapsed, ~21 min left)

[18:16:12] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:16:12] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:16:12] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:16:12] Explicit valence for atom # 7 C, 5, is greater than permitted

[2025/2737] (3492s elapsed, ~20 min left)

[18:16:41] Explicit valence for atom # 9 C, 5, is greater than permitted
[18:16:41] Explicit valence for atom # 9 C, 5, is greater than permitted
[18:16:41] Explicit valence for atom # 9 C, 5, is greater than permitted
[18:16:41] Explicit valence for atom # 9 C, 5, is greater than permitted
[18:17:08] Explicit valence for atom # 8 C, 5, is greater than permitted
[18:17:08] Explicit valence for atom # 8 C, 5, is greater than permitted

[2050/2737] (3539s elapsed, ~20 min left)

[18:17:17] Explicit valence for atom # 0 Si, 6, is greater than permitted
[18:17:17] Explicit valence for atom # 0 Si, 6, is greater than permitted
[18:17:17] Explicit valence for atom # 0 Si, 6, is greater than permitted
[18:17:17] Explicit valence for atom # 0 Si, 6, is greater than permitted
[18:17:19] Explicit valence for atom # 0 Si, 6, is greater than permitted
[18:17:19] Explicit valence for atom # 0 Si, 6, is greater than permitted
[18:17:19] Explicit valence for atom # 0 Si, 6, is greater than permitted
[18:17:19] Explicit valence for atom # 0 Si, 6, is greater than permitted
[18:17:22] Explicit valence for atom # 9 C, 5, is greater than permitted
[18:17:22] Explicit valence for atom # 9 C, 5, is greater than permitted
[18:17:22] Explicit valence for atom # 9 C, 5, is greater than permitted
[18:17:22] Explicit valence for atom # 9 C, 5, is greater than permitted
[18:17:25] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:17:25] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:17:25] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:17:25] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:17:25] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:17:25] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:17:25] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:17:25] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:17:27] Explicit valence for atom # 64 H, 2, is greater than permitted
[18:17:33] Explicit valence for atom # 16 C, 5, is greater than permitted
[18:17:33] Explicit valence for atom # 16 C, 5, is greater than permitted
[18:17:34] Explicit valence for atom # 16 C, 5, is greater than permitted
[18:17:34] Explicit valence for atom # 16 C, 5, is greater than permitted
[18:17:36] Explicit valence for atom # 0 H, 2, is greater than permitted
[18:17:36] Explicit valence for atom # 0 H, 2, is greater than permitted
[18:17:36] Explicit valence for atom # 0 H, 2, is greater than permitted
[18:17:36] Explicit valence for atom # 0 H, 2, is greater than permitted
[18:17:40] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:17:40] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:17:40] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:17:40] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:17:41] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:17:41] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:17:41] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:17:41] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:17:43] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:17:43] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:17:44] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:17:44] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:17:46] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:17:46] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:17:46] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:17:46] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:17:47] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:17:47] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:17:47] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:17:47] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:17:49] Explicit valence for atom # 10 N, 4, is greater than permitted
[18:17:49] Explicit valence for atom # 10 N, 4, is greater than permitted
[18:17:49] Explicit valence for atom # 10 N, 4, is greater than permitted
[18:17:49] Explicit valence for atom # 10 N, 4, is greater than permitted
[18:17:49] Explicit valence for atom # 10 N, 4, is greater than permitted
[18:17:49] Explicit valence for atom # 10 N, 4, is greater than permitted

[2075/2737] (3574s elapsed, ~19 min left)

[18:17:51] Explicit valence for atom # 30 C, 5, is greater than permitted
[18:17:51] Explicit valence for atom # 30 C, 5, is greater than permitted
[18:17:53] Explicit valence for atom # 30 C, 5, is greater than permitted
[18:17:53] Explicit valence for atom # 30 C, 5, is greater than permitted
[18:17:58] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:17:58] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:17:58] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:17:58] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:17:58] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:17:58] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:17:58] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:17:58] Explicit valence for atom # 7 C, 5, is greater than permitted

[2100/2737] (3618s elapsed, ~18 min left)

[18:18:38] Explicit valence for atom # 14 C, 5, is greater than permitted
[18:18:38] Explicit valence for atom # 14 C, 5, is greater than permitted
[18:18:45] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:18:45] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:18:45] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:18:45] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:18:50] Explicit valence for atom # 21 C, 5, is greater than permitted
[18:18:50] Explicit valence for atom # 21 C, 5, is greater than permitted
[18:18:50] Explicit valence for atom # 21 C, 5, is greater than permitted
[18:18:50] Explicit valence for atom # 21 C, 5, is greater than permitted
[18:18:51] Explicit valence for atom # 21 C, 5, is greater than permitted
[18:18:51] Explicit valence for atom # 21 C, 5, is greater than permitted
[18:18:51] Explicit valence for atom # 21 C, 5, is greater than permitted
[18:18:51] Explicit valence for atom # 21 C, 5, is greater than permitted

[2125/2737] (3655s elapsed, ~18 min left)

[18:19:28] Explicit valence for atom # 14 C, 5, is greater than permitted
[18:19:28] Explicit valence for atom # 14 C, 5, is greater than permitted
[18:19:28] Explicit valence for atom # 14 C, 5, is greater than permitted
[18:19:28] Explicit valence for atom # 14 C, 5, is greater than permitted
[18:19:28] Explicit valence for atom # 18 C, 5, is greater than permitted
[18:19:28] Explicit valence for atom # 18 C, 5, is greater than permitted
[18:19:31] Explicit valence for atom # 14 C, 5, is greater than permitted
[18:19:31] Explicit valence for atom # 14 C, 5, is greater than permitted
[18:19:31] Explicit valence for atom # 14 C, 5, is greater than permitted
[18:19:31] Explicit valence for atom # 14 C, 5, is greater than permitted
[18:19:31] Explicit valence for atom # 18 C, 5, is greater than permitted
[18:19:31] Explicit valence for atom # 18 C, 5, is greater than permitted
[18:19:33] Explicit valence for atom # 8 C, 5, is greater than permitted
[18:19:33] Explicit valence for atom # 8 C, 5, is greater than permitted
[18:19:33] Explicit valence for atom # 8 C, 5, is greater than permitted
[18:19:34] Explicit valence for atom # 8 C, 5, is greater than permitted
[18:19:34] Explicit valence for atom # 8 C, 5, is greater than permitted
[18:19:34] Explicit valence for atom # 8 C, 5, is greater than permitted
[18:19:37] Explicit valence for atom # 24 C, 5, is greater than permitted
[18:19:37] Explicit valence for atom # 24 C, 5, is greater than permitted
[18:19:40] Explicit valence for atom # 24 C, 5, is greater than permitted
[18:19:40] Explicit valence for atom # 24 C, 5, is greater than permitted
[18:19:42] Explicit valence for atom # 27 C, 5, is greater than permitted
[18:19:42] Explicit valence for atom # 27 C, 5, is greater than permitted
[18:19:42] Explicit valence for atom # 27 C, 5, is greater than permitted
[18:19:42] Explicit valence for atom # 27 C, 5, is greater than permitted
[18:19:43] Explicit valence for atom # 27 C, 5, is greater than permitted
[18:19:43] Explicit valence for atom # 27 C, 5, is greater than permitted
[18:19:43] Explicit valence for atom # 27 C, 5, is greater than permitted
[18:19:43] Explicit valence for atom # 27 C, 5, is greater than permitted
[18:19:53] Explicit valence for atom # 23 C, 5, is greater than permitted
[18:19:53] Explicit valence for atom # 23 C, 5, is greater than permitted
[18:19:55] Explicit valence for atom # 23 C, 5, is greater than permitted
[18:19:55] Explicit valence for atom # 23 C, 5, is greater than permitted

[2150/2737] (3701s elapsed, ~17 min left)

[18:20:03] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:20:03] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:20:03] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:20:03] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:20:06] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:20:06] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:20:06] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:20:06] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:20:08] Explicit valence for atom # 4 C, 5, is greater than permitted
[18:20:08] Explicit valence for atom # 4 C, 5, is greater than permitted
[18:20:18] Explicit valence for atom # 49 C, 6, is greater than permitted
[18:20:18] Explicit valence for atom # 10 O, 3, is greater than permitted
[18:20:18] Explicit valence for atom # 49 C, 6, is greater than permitted
[18:20:18] Explicit valence for atom # 10 O, 3, is greater than permitted

[2175/2737] (3734s elapsed, ~16 min left)

[18:20:45] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:20:45] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:20:45] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:20:45] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:20:47] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:20:47] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:20:47] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:20:47] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:20:48] Explicit valence for atom # 4 C, 5, is greater than permitted
[18:20:48] Explicit valence for atom # 4 C, 5, is greater than permitted
[18:20:48] Explicit valence for atom # 4 C, 5, is greater than permitted
[18:20:48] Explicit valence for atom # 4 C, 5, is greater than permitted
[18:20:48] Explicit valence for atom # 4 C, 5, is greater than permitted
[18:20:48] Explicit valence for atom # 4 C, 5, is greater than permitted
[18:20:57] Explicit valence for atom # 1 O, 3, is greater than permitted
[18:20:57] Explicit valence for atom # 1 O, 3, is greater than permitted
[18:20:58] Explicit valence for atom # 1 O, 3, is greater than permitted
[18:20:58] Explicit valence for atom # 1 O, 3, is greater than permitted
[18:21:07] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:21:07] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:21:07] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:21:07] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:21:07] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:21:07] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:21:07] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:21:07] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:21:11] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:21:11] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:21:11] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:21:11] Explicit valence for atom # 7 C, 5, is greater than permitted

[2200/2737] (3780s elapsed, ~15 min left)

[18:21:17] Explicit valence for atom # 10 C, 5, is greater than permitted
[18:21:17] Explicit valence for atom # 10 C, 5, is greater than permitted
[18:21:17] Explicit valence for atom # 10 C, 5, is greater than permitted
[18:21:17] Explicit valence for atom # 10 C, 5, is greater than permitted
[18:21:20] Explicit valence for atom # 39 C, 5, is greater than permitted
[18:21:20] Explicit valence for atom # 39 C, 5, is greater than permitted
[18:21:20] Explicit valence for atom # 39 C, 5, is greater than permitted
[18:21:20] Explicit valence for atom # 39 C, 5, is greater than permitted
[18:21:23] Explicit valence for atom # 1 N, 5, is greater than permitted
[18:21:23] Explicit valence for atom # 1 N, 5, is greater than permitted
[18:21:23] Explicit valence for atom # 1 N, 5, is greater than permitted
[18:21:23] Explicit valence for atom # 1 N, 5, is greater than permitted
[18:21:24] Explicit valence for atom # 1 N, 5, is greater than permitted
[18:21:24] Explicit valence for atom # 1 N, 5, is greater than permitted
[18:21:24] Explicit valence for atom # 1 N, 5, is greater than permitted
[18:21:24] Explicit valence for atom # 1 N, 5, is greater than permitted
[18:21:25] Explicit valence for atom # 11 C, 5, is greater than permitted
[18:21:25] Explicit valence for atom # 11 C, 5, is greater than permitted
[18:21:25] Explicit valence for atom # 11 C, 5, is greater than permitted
[18:21:25] Explicit valence for atom # 11 C, 5, is greater than permitted
[18:21:27] Explicit valence for atom # 9 C, 6, is greater than permitted
[18:21:27] Explicit valence for atom # 9 C, 6, is greater than permitted
[18:21:27] Explicit valence for atom # 9 C, 6, is greater than permitted
[18:21:27] Explicit valence for atom # 9 C, 6, is greater than permitted
[18:21:28] Explicit valence for atom # 9 C, 6, is greater than permitted
[18:21:28] Explicit valence for atom # 9 C, 6, is greater than permitted
[18:21:28] Explicit valence for atom # 9 C, 6, is greater than permitted
[18:21:28] Explicit valence for atom # 9 C, 5, is greater than permitted
[18:21:28] Explicit valence for atom # 9 C, 5, is greater than permitted
[18:21:28] Explicit valence for atom # 9 C, 5, is greater than permitted
[18:21:28] Explicit valence for atom # 9 C, 5, is greater than permitted
[18:21:28] Explicit valence for atom # 9 C, 6, is greater than permitted
[18:21:30] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:21:30] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:21:30] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:21:30] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:21:50] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:21:50] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:21:50] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:21:50] Explicit valence for atom # 7 C, 5, is greater than permitted

[2225/2737] (3822s elapsed, ~15 min left)

[18:22:01] Explicit valence for atom # 16 C, 5, is greater than permitted
[18:22:01] Explicit valence for atom # 16 C, 5, is greater than permitted
[18:22:01] Explicit valence for atom # 16 C, 5, is greater than permitted
[18:22:01] Explicit valence for atom # 16 C, 5, is greater than permitted

[2250/2737] (3863s elapsed, ~14 min left)

[18:22:46] Explicit valence for atom # 0 B, 4, is greater than permitted
[18:22:46] Explicit valence for atom # 0 B, 4, is greater than permitted
[18:22:46] Explicit valence for atom # 0 B, 4, is greater than permitted
[18:22:46] Explicit valence for atom # 0 B, 4, is greater than permitted
[18:22:48] Explicit valence for atom # 0 B, 4, is greater than permitted
[18:22:48] Explicit valence for atom # 0 B, 4, is greater than permitted
[18:22:48] Explicit valence for atom # 0 B, 4, is greater than permitted
[18:22:48] Explicit valence for atom # 0 B, 4, is greater than permitted
[18:22:48] Explicit valence for atom # 11 C, 5, is greater than permitted
[18:22:48] Explicit valence for atom # 11 C, 5, is greater than permitted
[18:22:48] Explicit valence for atom # 11 C, 5, is greater than permitted
[18:22:48] Explicit valence for atom # 11 C, 5, is greater than permitted
[18:22:50] Explicit valence for atom # 0 B, 4, is greater than permitted
[18:22:50] Explicit valence for atom # 0 B, 4, is greater than permitted
[18:22:50] Explicit valence for atom # 0 B, 4, is greater than permitted
[18:22:50] Explicit valence for atom # 0 B, 4, is greater than permitted
[18:22:50] Explicit valence for atom # 0 B, 4, is greater than permitted
[18:22:50] Explicit valence for atom # 0 B, 4, is greater than permitted
[18:22:50] Explicit valence for atom # 0 B, 4, is greater than permitted
[18:22:50] Explicit valence for atom # 0 B, 4, is greater than permitted
[18:22:52] Explicit valence for atom # 0 B, 4, is greater than permitted
[18:22:53] Explicit valence for atom # 0 B, 4, is greater than permitted
[18:22:53] Explicit valence for atom # 0 B, 4, is greater than permitted
[18:22:53] Explicit valence for atom # 0 B, 4, is greater than permitted
[18:22:53] Explicit valence for atom # 0 B, 4, is greater than permitted
[18:22:53] Explicit valence for atom # 0 B, 4, is greater than permitted
[18:22:53] Explicit valence for atom # 0 B, 4, is greater than permitted
[18:22:53] Explicit valence for atom # 0 B, 4, is greater than permitted
[18:22:54] Explicit valence for atom # 12 H, 2, is greater than permitted
[18:22:54] Explicit valence for atom # 12 H, 2, is greater than permitted
[18:22:56] Explicit valence for atom # 11 C, 6, is greater than permitted
[18:22:56] Explicit valence for atom # 11 C, 6, is greater than permitted
[18:22:57] Explicit valence for atom # 11 C, 6, is greater than permitted
[18:22:57] Explicit valence for atom # 11 C, 6, is greater than permitted
[18:22:59] Explicit valence for atom # 4 C, 5, is greater than permitted
[18:22:59] Explicit valence for atom # 4 C, 5, is greater than permitted
[18:22:59] Explicit valence for atom # 4 C, 5, is greater than permitted
[18:22:59] Explicit valence for atom # 4 C, 5, is greater than permitted
[18:22:59] Explicit valence for atom # 4 C, 6, is greater than permitted
[18:22:59] Explicit valence for atom # 4 C, 6, is greater than permitted
[18:22:59] Explicit valence for atom # 4 C, 6, is greater than permitted
[18:22:59] Explicit valence for atom # 4 C, 6, is greater than permitted
[18:23:01] Explicit valence for atom # 4 C, 5, is greater than permitted
[18:23:01] Explicit valence for atom # 4 C, 5, is greater than permitted
[18:23:01] Explicit valence for atom # 4 C, 5, is greater than permitted
[18:23:01] Explicit valence for atom # 4 C, 5, is greater than permitted
[18:23:01] Explicit valence for atom # 4 C, 6, is greater than permitted
[18:23:01] Explicit valence for atom # 4 C, 6, is greater than permitted
[18:23:01] Explicit valence for atom # 4 C, 6, is greater than permitted
[18:23:01] Explicit valence for atom # 4 C, 6, is greater than permitted
[18:23:03] Explicit valence for atom # 22 C, 5, is greater than permitted
[18:23:03] Explicit valence for atom # 22 C, 5, is greater than permitted
[18:23:04] Explicit valence for atom # 22 C, 5, is greater than permitted
[18:23:04] Explicit valence for atom # 22 C, 5, is greater than permitted

[2275/2737] (4342s elapsed, ~15 min left)

[18:30:37] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:37] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:37] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:37] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:37] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:37] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:37] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:37] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:37] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:37] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:37] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:37] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:37] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:37] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:37] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:37] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:37] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:37] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:37] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:37] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:37] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:37] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:37] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:37] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:40] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:40] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:40] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:40] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:40] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:40] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:40] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:40] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:40] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:40] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:40] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:40] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:40] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:40] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:40] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:40] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:40] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:40] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:40] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:40] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:40] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:40] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:40] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:30:40] Explicit valence for atom # 4 N, 4, is greater than permitted
[18:31:01] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:31:01] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:31:01] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:31:01] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:31:01] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:31:01] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:31:02] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:31:02] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:31:02] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:31:02] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:31:02] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:31:02] Explicit valence for atom # 6 C, 5, is greater than permitted
[18:31:04] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:04] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:04] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:04] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:04] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:04] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:04] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:04] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:06] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:06] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:06] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:06] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:06] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:06] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:06] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:06] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:11] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:11] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:11] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:11] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:11] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:11] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:11] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:11] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:13] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:13] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:13] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:13] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:13] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:13] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:13] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:13] Explicit valence for atom # 17 C, 5, is greater than permitted

[2300/2737] (4383s elapsed, ~14 min left)

[18:31:22] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:22] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:22] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:22] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:22] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:22] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:22] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:22] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:24] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:24] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:24] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:24] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:24] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:24] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:24] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:24] Explicit valence for atom # 17 C, 5, is greater than permitted
[18:31:52] Explicit valence for atom # 12 C, 5, is greater than permitted
[18:31:52] Explicit valence for atom # 12 C, 5, is greater than permitted
[18:31:52] Explicit valence for atom # 12 C, 5, is greater than permitted
[18:31:52] Explicit valence for atom # 12 C, 5, is greater than permitted
[18:31:52] Explicit valence for atom # 12 C, 5, is greater than permitted
[18:31:52] Explicit valence for atom # 12 C, 5, is greater than permitted
[18:31:53] Explicit valence for atom # 12 C, 5, is greater than permitted
[18:31:53] Explicit valence for atom # 12 C, 5, is greater than permitted
[18:31:53] Explicit valence for atom # 12 C, 5, is greater than permitted
[18:31:53] Explicit valence for atom # 12 C, 5, is greater than permitted
[18:31:53] Explicit valence for atom # 12 C, 5, is greater than permitted
[18:31:53] Explicit valence for atom # 12 C, 5, is greater than permitted

[2325/2737] (4421s elapsed, ~13 min left)

[18:32:02] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:32:02] Explicit valence for atom # 10 C, 5, is greater than permitted
[18:32:02] Explicit valence for atom # 10 C, 5, is greater than permitted
[18:32:02] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:32:02] Explicit valence for atom # 10 C, 5, is greater than permitted
[18:32:02] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:32:04] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:32:04] Explicit valence for atom # 10 C, 5, is greater than permitted
[18:32:04] Explicit valence for atom # 10 C, 5, is greater than permitted
[18:32:04] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:32:04] Explicit valence for atom # 10 C, 5, is greater than permitted
[18:32:04] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:32:06] Explicit valence for atom # 54 C, 5, is greater than permitted
[18:32:06] Explicit valence for atom # 38 C, 5, is greater than permitted
[18:32:06] Explicit valence for atom # 54 C, 5, is greater than permitted
[18:32:06] Explicit valence for atom # 38 C, 5, is greater than permitted
[18:32:07] Explicit valence for atom # 33 C, 5, is greater than permitted
[18:32:07] Explicit valence for atom # 33 C, 5, is greater than permitted
[18:32:07] Explicit valence for atom # 33 C, 5, is greater than permitted
[18:32:07] Explicit valence for atom # 33 C, 5, is greater than permitted
[18:32:08] Explicit valence for atom # 33 C, 5, is greater than permitted
[18:32:08] Explicit valence for atom # 33 C, 5, is greater than permitted
[18:32:08] Explicit valence for atom # 33 C, 5, is greater than permitted
[18:32:08] Explicit valence for atom # 33 C, 5, is greater than permitted
[18:32:09] Explicit valence for atom # 4 C, 5, is greater than permitted
[18:32:09] Explicit valence for atom # 4 C, 5, is greater than permitted
[18:32:10] Explicit valence for atom # 4 C, 5, is greater than permitted
[18:32:11] Explicit valence for atom # 4 C, 5, is greater than permitted
[18:32:13] Explicit valence for atom # 38 C, 5, is greater than permitted
[18:32:13] Explicit valence for atom # 38 C, 5, is greater than permitted
[18:32:13] Explicit valence for atom # 38 C, 5, is greater than permitted
[18:32:13] Explicit valence for atom # 38 C, 5, is greater than permitted
[18:32:13] Explicit valence for atom # 38 C, 5, is greater than permitted
[18:32:13] Explicit valence for atom # 38 C, 5, is greater than permitted
[18:32:13] Explicit valence for atom # 38 C, 5, is greater than permitted
[18:32:13] Explicit valence for atom # 38 C, 5, is greater than permitted
[18:32:14] Explicit valence for atom # 38 C, 5, is greater than permitted
[18:32:14] Explicit valence for atom # 38 C, 5, is greater than permitted
[18:32:14] Explicit valence for atom # 38 C, 5, is greater than permitted
[18:32:14] Explicit valence for atom # 38 C, 5, is greater than permitted
[18:32:14] Explicit valence for atom # 38 C, 5, is greater than permitted
[18:32:14] Explicit valence for atom # 38 C, 5, is greater than permitted
[18:32:14] Explicit valence for atom # 38 C, 5, is greater than permitted
[18:32:14] Explicit valence for atom # 38 C, 5, is greater than permitted

[2350/2737] (4457s elapsed, ~12 min left)
[2375/2737] (4496s elapsed, ~11 min left)

[18:33:20] Explicit valence for atom # 4 C, 5, is greater than permitted
[18:33:20] Explicit valence for atom # 4 C, 5, is greater than permitted
[18:33:22] Explicit valence for atom # 4 C, 5, is greater than permitted
[18:33:22] Explicit valence for atom # 4 C, 5, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted
[18:33:46] Explicit valence for atom # 39 C, 6, is greater than permitted

[2400/2737] (4542s elapsed, ~11 min left)

[18:34:01] Explicit valence for atom # 11 C, 5, is greater than permitted
[18:34:01] Explicit valence for atom # 11 C, 5, is greater than permitted
[18:34:01] Explicit valence for atom # 11 C, 5, is greater than permitted
[18:34:01] Explicit valence for atom # 11 C, 5, is greater than permitted
[18:34:01] Explicit valence for atom # 11 C, 5, is greater than permitted
[18:34:01] Explicit valence for atom # 11 C, 5, is greater than permitted
[18:34:02] Explicit valence for atom # 46 C, 5, is greater than permitted
[18:34:02] Explicit valence for atom # 46 C, 5, is greater than permitted
[18:34:05] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:34:05] Explicit valence for atom # 9 N, 4, is greater than permitted
[18:34:05] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:34:05] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:34:05] Explicit valence for atom # 9 N, 4, is greater than permitted
[18:34:05] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:34:05] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:34:05] Explicit valence for atom # 9 N, 4, is greater than permitted
[18:34:05] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:34:05] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:34:05] Explicit valence for atom # 9 N, 4, is greater than permitted
[18:34:05] Explicit valence for atom # 7 C, 5, is greater than permitted
[18:34:22] Explicit valence for atom # 17 O, 3, is greater than permitted
[18:34:22] Explicit valence for atom # 17 O, 3, is greater than permitted
[18:34:22] Explicit valence for atom # 17 O, 3, is greater than permitted
[18:34:22] Explicit valence for atom # 17 O, 3, is greater than permitted
[18:34:22] Explicit valence for atom # 17 O, 3, is greater than permitted
[18:34:22] Explicit valence for atom # 17 O, 3, is greater than permitted
[18:34:22] Explicit valence for atom # 17 O, 3, is greater than permitted
[18:34:22] Explicit valence for atom # 17 O, 3, is greater than permitted
[18:34:22] Explicit valence for atom # 17 O, 3, is greater than permitted
[18:34:22] Explicit valence for atom # 17 O, 3, is greater than permitted
[18:34:22] Explicit valence for atom # 17 O, 3, is greater than permitted
[18:34:22] Explicit valence for atom # 17 O, 3, is greater than permitted
[18:34:33] Explicit valence for atom # 0 Si, 6, is greater than permitted
[18:34:33] Explicit valence for atom # 0 Si, 6, is greater than permitted

[2425/2737] (4580s elapsed, ~10 min left)

[18:34:35] Explicit valence for atom # 0 Si, 6, is greater than permitted
[18:34:35] Explicit valence for atom # 0 Si, 6, is greater than permitted
[18:34:36] Explicit valence for atom # 2 C, 5, is greater than permitted
[18:34:36] Explicit valence for atom # 2 C, 5, is greater than permitted
[18:34:36] Explicit valence for atom # 2 C, 5, is greater than permitted
[18:34:36] Explicit valence for atom # 2 C, 5, is greater than permitted
[18:34:36] Explicit valence for atom # 2 C, 5, is greater than permitted
[18:34:36] Explicit valence for atom # 2 C, 5, is greater than permitted
[18:34:38] Explicit valence for atom # 2 C, 5, is greater than permitted
[18:34:38] Explicit valence for atom # 2 C, 5, is greater than permitted
[18:34:38] Explicit valence for atom # 2 C, 5, is greater than permitted
[18:34:38] Explicit valence for atom # 2 C, 5, is greater than permitted
[18:34:38] Explicit valence for atom # 2 C, 5, is greater than permitted
[18:34:38] Explicit valence for atom # 2 C, 5, is greater than permitted
[18:35:03] Explicit valence for atom # 8 C, 5, is greater than permitted
[18:35:03] Explicit valence for atom # 8 C, 5, is greater than permitted
[18:35:03] Explicit valence for atom # 8 C, 5, is greater than permitted
[18:35:03] Explicit valence for atom # 8 C, 5, is greater than permitted
[18:35:04] Explicit valence for atom # 8 C, 5, is greater than permitted
[18:35:04] Explicit valence for atom # 8 C, 5, is greater than permitted
[18:35:04] Explicit valence for atom # 8 C, 5, is greater than permitted
[18:35:04] Explicit valence for atom # 8 C, 5, is greater than permitted
[18:35:06] Explicit valence for atom # 16 C, 6, is greater than permitted
[18:35:06] Explicit valence for atom # 16 C, 6, is greater than permitted
[18:35:07] Explicit valence for atom # 16 C, 6, is greater than permitted
[18:35:07] Explicit valence for atom # 16 C, 6, is greater than permitted

[2450/2737] (4651s elapsed, ~9 min left)

[18:36:09] Explicit valence for atom # 12 C, 5, is greater than permitted
[18:36:11] Explicit valence for atom # 12 C, 5, is greater than permitted

[2475/2737] (4696s elapsed, ~8 min left)

[18:38:01] Explicit valence for atom # 0 Si, 6, is greater than permitted
[18:38:01] Explicit valence for atom # 0 Si, 6, is greater than permitted
[18:38:01] Explicit valence for atom # 0 Si, 6, is greater than permitted
[18:38:01] Explicit valence for atom # 0 Si, 6, is greater than permitted
[18:38:07] Explicit valence for atom # 0 Si, 6, is greater than permitted
[18:38:07] Explicit valence for atom # 0 Si, 6, is greater than permitted
[18:38:07] Explicit valence for atom # 0 Si, 6, is greater than permitted
[18:38:07] Explicit valence for atom # 0 Si, 6, is greater than permitted
[18:38:08] Explicit valence for atom # 0 Si, 6, is greater than permitted
[18:38:08] Explicit valence for atom # 0 Si, 6, is greater than permitted
[18:38:08] Explicit valence for atom # 0 Si, 6, is greater than permitted
[18:38:08] Explicit valence for atom # 0 Si, 6, is greater than permitted
[18:38:09] Explicit valence for atom # 0 Si, 6, is greater than permitted
[18:38:09] Explicit valence for atom # 0 Si, 6, is greater than permitted
[18:38:09] Explicit valence for atom # 0 Si, 6, is greater than permitted
[18:38:09] Explicit valence for atom # 0 Si, 6, is greater than permitted

[2500/2737] (4818s elapsed, ~8 min left)

[18:58:36] Explicit valence for atom # 1 O, 3, is greater than permitted
[18:58:36] Explicit valence for atom # 1 O, 3, is greater than permitted
[18:58:36] Explicit valence for atom # 1 O, 3, is greater than permitted
[18:58:36] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:58:36] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:58:37] Explicit valence for atom # 1 O, 3, is greater than permitted
[18:58:37] Explicit valence for atom # 1 O, 3, is greater than permitted
[18:58:37] Explicit valence for atom # 1 O, 3, is greater than permitted
[18:58:38] Explicit valence for atom # 1 O, 3, is greater than permitted
[18:58:38] Explicit valence for atom # 1 O, 3, is greater than permitted
[18:58:38] Explicit valence for atom # 1 O, 3, is greater than permitted
[18:58:38] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:58:38] Explicit valence for atom # 0 N, 4, is greater than permitted
[18:58:38] Explicit valence for atom # 1 O, 3, is greater than permitted
[18:58:38] Explicit valence for atom # 1 O, 3, is greater than permitted
[18:58:38] Explicit valence for atom # 1 O, 3, is greater than permitted

[2525/2737] (6028s elapsed, ~8 min left)
[2550/2737] (6624s elapsed, ~8 min left)

[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:39] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted
[19:08:43] Explicit valence for atom # 13 N, 4, is greater than permitted

[2575/2737] (6677s elapsed, ~7 min left)
[2600/2737] (6720s elapsed, ~6 min left)

[19:10:34] Explicit valence for atom # 8 C, 5, is greater than permitted
[19:10:34] Explicit valence for atom # 8 C, 5, is greater than permitted
[19:10:36] Explicit valence for atom # 8 C, 5, is greater than permitted
[19:10:36] Explicit valence for atom # 8 C, 5, is greater than permitted
[19:10:49] Explicit valence for atom # 0 Si, 6, is greater than permitted
[19:10:49] Explicit valence for atom # 0 Si, 6, is greater than permitted
[19:10:49] Explicit valence for atom # 0 Si, 6, is greater than permitted
[19:10:49] Explicit valence for atom # 0 Si, 6, is greater than permitted
[19:10:50] Explicit valence for atom # 0 Si, 6, is greater than permitted
[19:10:50] Explicit valence for atom # 0 Si, 6, is greater than permitted
[19:10:50] Explicit valence for atom # 0 Si, 6, is greater than permitted
[19:10:50] Explicit valence for atom # 0 Si, 6, is greater than permitted

[2625/2737] (6763s elapsed, ~5 min left)

[19:11:19] Explicit valence for atom # 4 C, 5, is greater than permitted
[19:11:19] Explicit valence for atom # 4 C, 5, is greater than permitted
[19:11:21] Explicit valence for atom # 11 C, 5, is greater than permitted
[19:11:22] Explicit valence for atom # 11 C, 5, is greater than permitted
[19:11:23] Explicit valence for atom # 5 C, 5, is greater than permitted
[19:11:25] Explicit valence for atom # 5 C, 5, is greater than permitted
[19:11:26] Explicit valence for atom # 4 C, 6, is greater than permitted
[19:11:27] Explicit valence for atom # 4 C, 6, is greater than permitted

[2650/2737] (6793s elapsed, ~4 min left)

[19:11:33] Explicit valence for atom # 4 C, 6, is greater than permitted
[19:11:34] Explicit valence for atom # 4 C, 6, is greater than permitted
[19:11:35] Explicit valence for atom # 9 C, 5, is greater than permitted
[19:11:37] Explicit valence for atom # 9 C, 5, is greater than permitted

[2675/2737] (6827s elapsed, ~3 min left)

[19:13:14] Explicit valence for atom # 27 C, 5, is greater than permitted
[19:13:14] Explicit valence for atom # 27 C, 5, is greater than permitted
[19:13:14] Explicit valence for atom # 27 C, 5, is greater than permitted
[19:13:14] Explicit valence for atom # 27 C, 5, is greater than permitted
[19:13:14] Explicit valence for atom # 27 C, 5, is greater than permitted
[19:13:14] Explicit valence for atom # 27 C, 5, is greater than permitted
[19:13:14] Explicit valence for atom # 27 C, 5, is greater than permitted
[19:13:14] Explicit valence for atom # 27 C, 5, is greater than permitted
[19:13:18] Explicit valence for atom # 27 C, 5, is greater than permitted
[19:13:18] Explicit valence for atom # 27 C, 5, is greater than permitted
[19:13:18] Explicit valence for atom # 27 C, 5, is greater than permitted
[19:13:18] Explicit valence for atom # 27 C, 5, is greater than permitted
[19:13:18] Explicit valence for atom # 27 C, 5, is greater than permitted
[19:13:18] Explicit valence for atom # 27 C, 5, is greater than permitted
[19:13:18] Explicit valence for atom # 27 C, 5, is greater than permitted
[19:13:18] Explicit valence for atom # 27 C, 5, is greater than permitted

[2700/2737] (6906s elapsed, ~2 min left)

[19:13:21] Explicit valence for atom # 10 C, 5, is greater than permitted
[19:13:21] Explicit valence for atom # 10 C, 5, is greater than permitted
[19:13:21] Explicit valence for atom # 10 C, 5, is greater than permitted
[19:13:21] Explicit valence for atom # 10 C, 5, is greater than permitted
[19:13:25] Explicit valence for atom # 10 C, 5, is greater than permitted
[19:13:25] Explicit valence for atom # 10 C, 5, is greater than permitted
[19:13:25] Explicit valence for atom # 10 C, 5, is greater than permitted
[19:13:25] Explicit valence for atom # 10 C, 5, is greater than permitted
[19:13:28] Explicit valence for atom # 10 C, 5, is greater than permitted
[19:13:28] Explicit valence for atom # 10 C, 5, is greater than permitted
[19:13:28] Explicit valence for atom # 10 C, 5, is greater than permitted
[19:13:28] Explicit valence for atom # 10 C, 5, is greater than permitted
[19:13:32] Explicit valence for atom # 10 C, 5, is greater than permitted
[19:13:32] Explicit valence for atom # 10 C, 5, is greater than permitted
[19:13:32] Explicit valence for atom # 10 C, 5, is greater than permitted
[19:13:32] Explicit valence for atom # 10 C, 5, is greater than permitted

[2725/2737] (6972s elapsed, ~1 min left)

[19:14:33] Explicit valence for atom # 8 C, 5, is greater than permitted
[19:14:33] Explicit valence for atom # 8 C, 5, is greater than permitted

done: 2737 converted this run

Build the final table -- 4 columns: filename, mofid, mofkey, mofjson (path to the schema file; the schema itself is too large to inline per-row for 2000+ structures).

In [4]:
import pandas as pd

rows = [json.loads(l) for l in open(RESULTS_JSONL) if l.strip()]
df = pd.DataFrame(rows)[["cif_filename", "mofid", "mofkey", "mofjson_path"]]
df.to_csv(RESULTS_TABLE, sep="\t", index=False)
print(f"wrote {len(df)} rows to {RESULTS_TABLE}")
df.head()

wrote 2737 rows to /Users/yong/projects/MoFJSON/dataset/mof_conversion_out/mof_conversion.tsv

,cif_filename,mofid,mofkey,mofjson_path
0,41467_2015_BFncomms7350_MOESM943_ESM_1_ASR_pac...,CC1=NN=C([N]1)CC1=[N]=C(N=N1)C.CC1=[N]=C(N=N1)...,Cu.BDWGWOFRNBKPSU.MOFkey-v1.UNKNOWN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
1,41467_2015_BFncomms7350_MOESM943_ESM_1_FSR_pac...,CC1=NN=C([N]1)CC1=[N]=C(N=N1)C.CC1=[N]=C(N=N1)...,Cu.BDWGWOFRNBKPSU.MOFkey-v1.UNKNOWN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
2,41467_2015_BFncomms7350_MOESM943_ESM_3_FSR_pac...,CC1=NN=C([N]1)CC1=[N]=C(N=N1)C.CC1=[N]=C(N=N1)...,Cu.BDWGWOFRNBKPSU.MOFkey-v1.UNKNOWN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
3,41467_2015_BFncomms7350_MOESM943_ESM_4_ASR_pac...,CC1=NN=C([N]1)CC1=[N]=C(N=N1)C.CC1=[N]=C(N=N1)...,Cu.BDWGWOFRNBKPSU.MOFkey-v1.UNKNOWN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
4,41467_2015_BFncomms7350_MOESM943_ESM_4_FSR_pac...,CC1=NN=C([N]1)CC1=[N]=C(N=N1)C.CC1=[N]=C(N=N1)...,Cu.BDWGWOFRNBKPSU.MOFkey-v1.UNKNOWN,/Users/yong/projects/MoFJSON/dataset/mof_conve...

In [7]:
df_tsv = pd.read_csv(RESULTS_TABLE, sep="\t")

cols = ["cif_filename", "mofid", "mofkey", "mofjson_path"]

print(f"Total Rows: {len(df_tsv)} (Expected: 2737)")
print("-" * 40)

# Check missing values for each representation
print("Missing / Null values per representation:")
print(df_tsv[cols].isna().sum())
print("-" * 40)

# Count unique values for each representation
print("Unique count per representation column:")
for col in cols:
    print(f"  • {col}: {df_tsv[col].nunique()} unique entries")

Total Rows: 2737 (Expected: 2737)
----------------------------------------
Missing / Null values per representation:
cif_filename     0
mofid           45
mofkey          45
mofjson_path     1
dtype: int64
----------------------------------------
Unique count per representation column:
  • cif_filename: 2737 unique entries
  • mofid: 2692 unique entries
  • mofkey: 1247 unique entries
  • mofjson_path: 2736 unique entries

In [8]:
# Filter for any row containing a NaN/None in the representation columns
missing_rows = df_tsv[df_tsv[["mofid", "mofkey", "mofjson_path"]].isna().any(axis=1)]

print(f"Found {len(missing_rows)} rows with missing data:")
missing_rows[["cif_filename", "mofid", "mofkey", "mofjson_path"]]

Found 46 rows with missing data:

,cif_filename,mofid,mofkey,mofjson_path
188,c5cc08456c2_1_ASR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
189,c5cc08456c2_1_FSR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
348,c6qi00526h2_ASR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
349,c6qi00526h2_FSR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
589,c7sc04266c2_ASR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
590,c7sc04266c2_FSR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
668,c8ce00692j2_7_FSR_pacman.cif,O=C(C1=CC=CC(=[C]1)c1ccc(c(c1)C(=O)[O-])C(=O)O...,Ni.LEOSWPQCDMBCNF.MWVTWFVJZLCBMC.NBAUUNCGSMAPF...,NaN
988,c9ce01567a2_1_ASR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
989,c9ce01567a2_3_ASR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
1049,c9dt02820j2_FSR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
1430,d0ra05131d2_1_ASR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
1431,d0ra05131d2_1_FSR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
1432,d0ra05131d2_4_ASR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
1433,d0ra05131d2_4_FSR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
1567,d1qi00683e2_1_ASR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
1568,d1qi00683e2_1_FSR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
1683,d2dt02968e2_1_ASR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
1684,d2dt02968e2_1_FSR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
1685,d2dt02968e2_2_ASR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
1686,d2dt02968e2_2_FSR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
1714,d2sc04324f2_ASR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
1715,d2sc04324f2_FSR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
1821,d3ce00881a2_7_ASR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
1822,d3ce00881a2_7_FSR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
2102,d4qi02396j2_2_ASR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
2139,d4ta06472k2_ASR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
2140,d4ta06472k2_FSR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
2268,ic6b02332_si_002_ASR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
2269,ic6b02332_si_002_FSR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
2270,ic6b02332_si_003_ASR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
2271,ic6b02332_si_003_FSR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
2280,ic6b03147_si_002_ASR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
2281,ic6b03147_si_002_FSR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
2382,ja0c09009_si_002_FSR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
2400,ja300034j_si_002_ASR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
2401,ja300034j_si_002_FSR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
2403,ja302380x_si_003_ASR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
2404,ja302380x_si_003_FSR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
2489,ja7b05858_si_010_ASR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
2490,ja7b05858_si_010_FSR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
2491,ja7b05858_si_013_ASR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
2500,ja7b09453_si_002_ASR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
2501,ja7b09453_si_002_FSR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
2502,ja7b09453_si_003_ASR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
2503,ja7b09453_si_003_FSR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...
2723,tz4c01131_si_002_1_FSR_pacman.cif,NaN,NaN,/Users/yong/projects/MoFJSON/dataset/mof_conve...