# MOF representation benchmark: CIF/MOfid/MofKey/MofJson

## 0) Setup

In [3]:
import json
import sys
import warnings
from pathlib import Path


def _find_project_root(start: Path) -> Path:
    for candidate in [start, *start.parents]:
        if (candidate / "src" / "mofjson").is_dir():
            return candidate
    raise RuntimeError(f"no src/mofjson found above {start}")


PROJECT_ROOT = _find_project_root(Path.cwd())
sys.path.insert(0, str(PROJECT_ROOT))

import pandas as pd
from pymatgen.io.cif import CifParser
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

from src.mofjson.topology import BuildTopologicalNet


def coordination_number(block_id, net_edges):
    return sum(1 for e in net_edges if e["from_block"] == block_id or e["to_block"] == block_id)


def _neg(shift):
    return tuple(-x for x in shift)


def _adjacency(net_edges):
    adj = {}
    for e in net_edges:
        s = tuple(e["shift"])
        adj.setdefault(e["from_block"], []).append((e["to_block"], s))
        adj.setdefault(e["to_block"], []).append((e["from_block"], _neg(s)))
    return adj


def shortest_net_path(start, target, net_edges, max_depth=20):
    if start == target:
        return 0
    adj = _adjacency(net_edges)
    visited = {(start, (0, 0, 0))}
    frontier = [(start, (0, 0, 0))]
    depth = 0
    while frontier and depth < max_depth:
        depth += 1
        nxt = []
        for block_id, cell in frontier:
            for nb, s in adj.get(block_id, []):
                if nb == target:
                    return depth
                new_cell = tuple(c + d for c, d in zip(cell, s))
                state = (nb, new_cell)
                if state not in visited:
                    visited.add(state)
                    nxt.append(state)
        frontier = nxt
    return None


def composition(block_id, building_block_dicts):
    block = next(b for b in building_block_dicts if b["id"] == block_id)
    return "/".join(sorted({a["element"] for a in block["atoms"] if a["element"] != "*"}))


CLOSING_INSTRUCTION = (
    "\n\nIf the answer cannot be determined from the information given below, "
    "set can_determine to false and value to null.\n\n"
    "Return JSON only matching the provided answer schema."
)


def make_answer_schema(value_type, value_description):
    return {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "can_determine": {
                "type": "boolean",
                "description": "Whether this question is answerable from the representation given below.",
            },
            "value": {"type": [value_type, "null"], "description": value_description},
        },
        "required": ["can_determine", "value"],
    }


def grade(representation, expected_answerable, ground_truth_value, model_answer):
    can_determine = model_answer.get("can_determine")
    value = model_answer.get("value")
    if expected_answerable:
        correct = (can_determine is True) and (value == ground_truth_value)
    else:
        correct = can_determine is False
    return {
        "representation": representation,
        "expected_answerable": expected_answerable,
        "model_can_determine": can_determine,
        "model_value": value,
        "ground_truth": ground_truth_value if expected_answerable else None,
        "correct": correct,
    }


def extract_reasoning_summary(resp):
    parts = []
    for item in getattr(resp, "output", []) or []:
        if getattr(item, "type", None) != "reasoning":
            continue
        for summary_item in getattr(item, "summary", []) or []:
            text = getattr(summary_item, "text", None)
            if isinstance(text, str):
                parts.append(text)
    return "\n\n".join(parts).strip()

## 1) Load a real MOF

In [4]:
MOF_CONVERSION_TSV = Path("/Users/yong/projects/MoFJSON/dataset/mof_conversion_out/mof_conversion.tsv")  # <-- edit this
CIF_DIR = Path("/Users/yong/projects/MoFJSON/dataset/CoreMOFDB/CR")  # <-- edit this if it moves
TARGET_CIF_FILENAME = "am6b14554_si_003_2_ASR_pacman.cif"  

manifest = pd.read_csv(MOF_CONVERSION_TSV, sep="\t")
clean = manifest[manifest["mofid"].notna() & (manifest["mofid"] != "") & manifest["mofjson_path"].notna()]

if TARGET_CIF_FILENAME:
    matches = manifest[manifest["cif_filename"] == TARGET_CIF_FILENAME]
    if matches.empty:
        raise ValueError(
            f"No row in the TSV has cif_filename == {TARGET_CIF_FILENAME!r}. "
            "TARGET_CIF_FILENAME must match the cif_filename column exactly "
            "(e.g. 'xxx.cif'), not a mofjson_path or any other column."
        )
    row = matches.iloc[0]
else:
    if clean.empty:
        raise ValueError("No rows in the TSV have both a non-empty mofid and a mofjson_path.")
    row = clean.iloc[0]

In [5]:
mofid_string = row["mofid"]
mofkey_string = row["mofkey"]
mofjson_path = Path(row["mofjson_path"])
cif_path = CIF_DIR / row["cif_filename"]

cif_text = cif_path.read_text()

with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    structure = CifParser(str(cif_path)).parse_structures(primitive=False)[0]

doc = json.loads(mofjson_path.read_text())
building_block_dicts = doc["derived"]["building_blocks"]

print("cif_filename:", row["cif_filename"])
print("mofid: ", mofid_string)
print("mofkey:", mofkey_string)
print(f"{len(building_block_dicts)} building blocks, net = {doc['derived']['topology'].get('net')}")

cif_filename: am6b14554_si_003_2_ASR_pacman.cif
mofid:  [Cd].[O-]C(=O)Cc1ccc(cc1)CC(=O)[O-].n1ccc(cc1)C1=NC(=[N]=C([N]1)c1ccncc1)c1ccncc1 MOFid-v1.sql.cat1;am6b14554_si_003_2_ASR_pacman
mofkey: Cd.CBMYFVSIIYILRH.SLWIPPZWFZGHEU.MOFkey-v1.sql
24 building blocks, net = None

## 2) Ground truth (computed here, independent of any model)

In [6]:
vertices, topo_edges, excluded = BuildTopologicalNet(building_block_dicts, doc["derived"]["net_edges"])

graph_payload = {
    "building_blocks": [
        {"id": b["id"], "formula": b["formula"]}
        for b in building_block_dicts if b["id"] in vertices
    ],
    "net_edges": [
        {"from_block": a, "to_block": b, "shift": list(s)}
        for a, b, s in topo_edges
    ],
}

# 2a) connectivity
COORD_TARGET_BLOCK = next(b["id"] for b in building_block_dicts if b["id"].startswith("node_") and b["id"] in vertices)
coord_target_composition = composition(COORD_TARGET_BLOCK, building_block_dicts)
ground_truth_connectivity = coordination_number(COORD_TARGET_BLOCK, graph_payload["net_edges"])
assert ground_truth_connectivity == doc["derived"]["topology"]["vertex_signatures"][COORD_TARGET_BLOCK]["degree"]

# 2b) net-path distance
node_ids = [b["id"] for b in building_block_dicts if b["id"].startswith("node_") and b["id"] in vertices]
compositions = {nid: composition(nid, building_block_dicts) for nid in node_ids}
distinct_types = sorted(set(compositions.values()))

if len(distinct_types) >= 2:
    type_a, type_b = distinct_types[0], distinct_types[1]
    PATH_START_BLOCK = next(nid for nid, c in compositions.items() if c == type_a)
    PATH_END_BLOCK = next(nid for nid, c in compositions.items() if c == type_b)
    path_same_type = False
else:
    PATH_START_BLOCK = node_ids[0]
    candidates = [nid for nid in node_ids if nid != PATH_START_BLOCK]
    distances = {nid: shortest_net_path(PATH_START_BLOCK, nid, graph_payload["net_edges"]) for nid in candidates}
    distances = {k: v for k, v in distances.items() if v is not None}
    PATH_END_BLOCK = min(distances, key=distances.get)
    path_same_type = True

ground_truth_path = shortest_net_path(PATH_START_BLOCK, PATH_END_BLOCK, graph_payload["net_edges"])

# 2c) chemical identity -- first linker with a successfully extracted formula;
# fall back to the connectivity target's own metal composition if none exist
linker_blocks = [b for b in building_block_dicts if b["id"].startswith("linker_") and b.get("formula")]
if linker_blocks:
    IDENTITY_TARGET_BLOCK = linker_blocks[0]["id"]
    ground_truth_identity = linker_blocks[0]["formula"]
    identity_kind = "linker_formula"
else:
    IDENTITY_TARGET_BLOCK = COORD_TARGET_BLOCK
    ground_truth_identity = coord_target_composition
    identity_kind = "node_metal"

# 2d) symmetry
sga = SpacegroupAnalyzer(structure, symprec=0.1)
ground_truth_crystal_system = sga.get_crystal_system()

print("connectivity target:", COORD_TARGET_BLOCK, f"({coord_target_composition})", "-> connectivity =", ground_truth_connectivity)
print("path:", PATH_START_BLOCK, "->", PATH_END_BLOCK, f"(same_type={path_same_type})", "-> length =", ground_truth_path)
print("identity target:", IDENTITY_TARGET_BLOCK, f"({identity_kind})", "-> ground truth =", ground_truth_identity)
print("crystal system:", ground_truth_crystal_system)

connectivity target: node_1 (Cd) -> connectivity = 5
path: node_1 -> node_4 (same_type=True) -> length = 1
identity target: linker_13 (linker_formula) -> ground truth = C10H8*5O4-2
crystal system: orthorhombic

## 3) OpenAI setup

In [7]:
# REQUIRES_OPENAI_API_KEY
from openai import OpenAI
import os

os.environ["OPENAI_API_KEY"] = "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"
  

client = OpenAI()
MODEL = "gpt-5-nano"

## 4) Question Category 1 (Connectivity)

In [8]:
CONNECTIVITY_SCHEMA = make_answer_schema(
    "integer",
    "The connectivity of the described SBU -- how many organic linkers coordinate directly to it.",
)
connectivity_expected = {"cif": True, "mofjson": True, "mofid": False, "mofkey": False}

connectivity_prompt_cif = (
    f"A metal-organic framework is given below as a CIF file. What is the connectivity of "
    f"the {coord_target_composition}-containing secondary building unit (SBU) -- how many "
    f"organic linkers coordinate directly to it?\n\n{cif_text}" + CLOSING_INSTRUCTION
)
connectivity_prompt_mofjson = (
    f"A metal-organic framework's periodic net is given below (building blocks + net_edges). "
    f"What is the connectivity of the {coord_target_composition}-containing SBU (labeled "
    f"'{COORD_TARGET_BLOCK}')?\n\nGraph:\n{json.dumps(graph_payload, indent=2)}" + CLOSING_INSTRUCTION
)
connectivity_prompt_mofid = (
    f"A MOFid identifier for a metal-organic framework is given below. What is the "
    f"connectivity of the {coord_target_composition}-containing SBU?\n\n{mofid_string}" + CLOSING_INSTRUCTION
)
connectivity_prompt_mofkey = (
    f"A MOFkey identifier for a metal-organic framework is given below. What is the "
    f"connectivity of the {coord_target_composition}-containing SBU?\n\n{mofkey_string}" + CLOSING_INSTRUCTION
)

In [9]:
# REQUIRES_OPENAI_API_KEY
connectivity_response_cif = client.responses.create(
    model=MODEL,
    reasoning={"effort": "high", "summary": "detailed"},
    input=connectivity_prompt_cif,
    text={"verbosity": "low", "format": {"type": "json_schema", "name": "MOFAnswer", "strict": True, "schema": CONNECTIVITY_SCHEMA}},
    store=False,
)
connectivity_answer_cif = json.loads(connectivity_response_cif.output_text)
print(json.dumps(connectivity_answer_cif, indent=2))

{
  "can_determine": true,
  "value": 8
}

In [10]:
# REQUIRES_OPENAI_API_KEY
connectivity_response_mofjson = client.responses.create(
    model=MODEL,
    reasoning={"effort": "high", "summary": "detailed"},
    input=connectivity_prompt_mofjson,
    text={"verbosity": "low", "format": {"type": "json_schema", "name": "MOFAnswer", "strict": True, "schema": CONNECTIVITY_SCHEMA}},
    store=False,
)
connectivity_answer_mofjson = json.loads(connectivity_response_mofjson.output_text)
print(json.dumps(connectivity_answer_mofjson, indent=2))

{
  "can_determine": true,
  "value": 2
}

In [11]:
# REQUIRES_OPENAI_API_KEY
connectivity_response_mofid = client.responses.create(
    model=MODEL,
    reasoning={"effort": "high", "summary": "detailed"},
    input=connectivity_prompt_mofid,
    text={"verbosity": "low", "format": {"type": "json_schema", "name": "MOFAnswer", "strict": True, "schema": CONNECTIVITY_SCHEMA}},
    store=False,
)
connectivity_answer_mofid = json.loads(connectivity_response_mofid.output_text)
print(json.dumps(connectivity_answer_mofid, indent=2))

{
  "can_determine": true,
  "value": 2
}

In [12]:
# REQUIRES_OPENAI_API_KEY
connectivity_response_mofkey = client.responses.create(
    model=MODEL,
    reasoning={"effort": "high", "summary": "detailed"},
    input=connectivity_prompt_mofkey,
    text={"verbosity": "low", "format": {"type": "json_schema", "name": "MOFAnswer", "strict": True, "schema": CONNECTIVITY_SCHEMA}},
    store=False,
)
connectivity_answer_mofkey = json.loads(connectivity_response_mofkey.output_text)
print(json.dumps(connectivity_answer_mofkey, indent=2))

{
  "can_determine": false,
  "value": null
}

In [13]:
# REQUIRES_OPENAI_API_KEY
import pandas as pd

connectivity_results = pd.DataFrame([
    grade("cif", connectivity_expected["cif"], ground_truth_connectivity, connectivity_answer_cif),
    grade("mofjson", connectivity_expected["mofjson"], ground_truth_connectivity, connectivity_answer_mofjson),
    grade("mofid", connectivity_expected["mofid"], ground_truth_connectivity, connectivity_answer_mofid),
    grade("mofkey", connectivity_expected["mofkey"], ground_truth_connectivity, connectivity_answer_mofkey),
])
connectivity_results

,representation,expected_answerable,model_can_determine,model_value,ground_truth,correct
0,cif,True,True,8.0,5.0,False
1,mofjson,True,True,2.0,5.0,False
2,mofid,False,True,2.0,NaN,False
3,mofkey,False,False,NaN,NaN,True

## 5) Question Category 2 (Net-path distance)

In [14]:
PATH_SCHEMA = make_answer_schema(
    "integer",
    "The fewest net edges connecting the two described building blocks, respecting periodic shifts.",
)
path_expected = {"cif": True, "mofjson": True, "mofid": False, "mofkey": False}

if path_same_type:
    path_description = (
        f"the shortest path, in net edges, from one {compositions[PATH_START_BLOCK]}-containing "
        f"SBU to its nearest periodic repeat of the same building block"
    )
else:
    path_description = (
        f"the shortest path, in net edges, from the {compositions[PATH_START_BLOCK]}-containing "
        f"SBU to the {compositions[PATH_END_BLOCK]}-containing SBU"
    )

path_prompt_cif = (
    f"Given the CIF file below, what is {path_description}?\n\n{cif_text}" + CLOSING_INSTRUCTION
)
path_prompt_mofjson = (
    f"Given the periodic net below, what is {path_description}? (Labeled '{PATH_START_BLOCK}' "
    f"and '{PATH_END_BLOCK}' in the graph.)\n\nGraph:\n{json.dumps(graph_payload, indent=2)}" + CLOSING_INSTRUCTION
)
path_prompt_mofid = (
    f"A MOFid identifier for a metal-organic framework is given below. What is "
    f"{path_description}?\n\n{mofid_string}" + CLOSING_INSTRUCTION
)
path_prompt_mofkey = (
    f"A MOFkey identifier for a metal-organic framework is given below. What is "
    f"{path_description}?\n\n{mofkey_string}" + CLOSING_INSTRUCTION
)

In [15]:
# REQUIRES_OPENAI_API_KEY
path_response_cif = client.responses.create(
    model=MODEL,
    reasoning={"effort": "high", "summary": "detailed"},
    input=path_prompt_cif,
    text={"verbosity": "low", "format": {"type": "json_schema", "name": "MOFAnswer", "strict": True, "schema": PATH_SCHEMA}},
    store=False,
)
path_answer_cif = json.loads(path_response_cif.output_text)
print(json.dumps(path_answer_cif, indent=2))

{
  "can_determine": false,
  "value": null
}

In [16]:
# REQUIRES_OPENAI_API_KEY
path_response_mofjson = client.responses.create(
    model=MODEL,
    reasoning={"effort": "high", "summary": "detailed"},
    input=path_prompt_mofjson,
    text={"verbosity": "low", "format": {"type": "json_schema", "name": "MOFAnswer", "strict": True, "schema": PATH_SCHEMA}},
    store=False,
)
path_answer_mofjson = json.loads(path_response_mofjson.output_text)
print(json.dumps(path_answer_mofjson, indent=2))

{
  "can_determine": true,
  "value": 1
}

In [17]:
# REQUIRES_OPENAI_API_KEY
path_response_mofid = client.responses.create(
    model=MODEL,
    reasoning={"effort": "high", "summary": "detailed"},
    input=path_prompt_mofid,
    text={"verbosity": "low", "format": {"type": "json_schema", "name": "MOFAnswer", "strict": True, "schema": PATH_SCHEMA}},
    store=False,
)
path_answer_mofid = json.loads(path_response_mofid.output_text)
print(json.dumps(path_answer_mofid, indent=2))

{
  "can_determine": false,
  "value": null
}

In [18]:
# REQUIRES_OPENAI_API_KEY
path_response_mofkey = client.responses.create(
    model=MODEL,
    reasoning={"effort": "high", "summary": "detailed"},
    input=path_prompt_mofkey,
    text={"verbosity": "low", "format": {"type": "json_schema", "name": "MOFAnswer", "strict": True, "schema": PATH_SCHEMA}},
    store=False,
)
path_answer_mofkey = json.loads(path_response_mofkey.output_text)
print(json.dumps(path_answer_mofkey, indent=2))

{
  "can_determine": false,
  "value": null
}

In [19]:
# REQUIRES_OPENAI_API_KEY
path_results = pd.DataFrame([
    grade("cif", path_expected["cif"], ground_truth_path, path_answer_cif),
    grade("mofjson", path_expected["mofjson"], ground_truth_path, path_answer_mofjson),
    grade("mofid", path_expected["mofid"], ground_truth_path, path_answer_mofid),
    grade("mofkey", path_expected["mofkey"], ground_truth_path, path_answer_mofkey),
])
path_results

,representation,expected_answerable,model_can_determine,model_value,ground_truth,correct
0,cif,True,False,NaN,1.0,False
1,mofjson,True,True,1.0,1.0,True
2,mofid,False,False,NaN,NaN,True
3,mofkey,False,False,NaN,NaN,True

## 6) Question Category 3 (Chemical identity)

In [20]:
IDENTITY_SCHEMA = make_answer_schema("string", "The requested chemical identity value, as a plain string.")
identity_expected = {"cif": True, "mofjson": True, "mofid": True, "mofkey": identity_kind == "node_metal"}

if identity_kind == "linker_formula":
    identity_question = "what is the molecular formula of the organic linker in this MOF"
else:
    identity_question = "what metal(s) make up the secondary building unit (SBU) in this MOF"

identity_target_block = next(b for b in building_block_dicts if b["id"] == IDENTITY_TARGET_BLOCK)

identity_prompt_cif = (
    f"Given the CIF file below, {identity_question}?\n\n{cif_text}" + CLOSING_INSTRUCTION
)
identity_prompt_mofjson = (
    f"Given this MOF building block, {identity_question}?\n\n"
    f"{json.dumps({'id': identity_target_block['id'], 'formula': identity_target_block['formula'], 'smiles': identity_target_block.get('smiles')}, indent=2)}"
    + CLOSING_INSTRUCTION
)
identity_prompt_mofid = (
    f"Given the MOFid below, {identity_question}?\n\n{mofid_string}" + CLOSING_INSTRUCTION
)
identity_prompt_mofkey = (
    f"Given the MOFkey below, {identity_question}?\n\n{mofkey_string}" + CLOSING_INSTRUCTION
)

In [21]:
# REQUIRES_OPENAI_API_KEY
identity_response_cif = client.responses.create(
    model=MODEL,
    reasoning={"effort": "high", "summary": "detailed"},
    input=identity_prompt_cif,
    text={"verbosity": "low", "format": {"type": "json_schema", "name": "MOFAnswer", "strict": True, "schema": IDENTITY_SCHEMA}},
    store=False,
)
identity_answer_cif = json.loads(identity_response_cif.output_text)
print(json.dumps(identity_answer_cif, indent=2))

{
  "can_determine": true,
  "value": "C28H20N6O4"
}

In [22]:
# REQUIRES_OPENAI_API_KEY
identity_response_mofjson = client.responses.create(
    model=MODEL,
    reasoning={"effort": "high", "summary": "detailed"},
    input=identity_prompt_mofjson,
    text={"verbosity": "low", "format": {"type": "json_schema", "name": "MOFAnswer", "strict": True, "schema": IDENTITY_SCHEMA}},
    store=False,
)
identity_answer_mofjson = json.loads(identity_response_mofjson.output_text)
print(json.dumps(identity_answer_mofjson, indent=2))

{
  "can_determine": true,
  "value": "C10H8*5O4-2"
}

In [23]:
# REQUIRES_OPENAI_API_KEY
identity_response_mofid = client.responses.create(
    model=MODEL,
    reasoning={"effort": "high", "summary": "detailed"},
    input=identity_prompt_mofid,
    text={"verbosity": "low", "format": {"type": "json_schema", "name": "MOFAnswer", "strict": True, "schema": IDENTITY_SCHEMA}},
    store=False,
)
identity_answer_mofid = json.loads(identity_response_mofid.output_text)
print(json.dumps(identity_answer_mofid, indent=2))

{
  "can_determine": false,
  "value": null
}

In [24]:
# REQUIRES_OPENAI_API_KEY
identity_response_mofkey = client.responses.create(
    model=MODEL,
    reasoning={"effort": "high", "summary": "detailed"},
    input=identity_prompt_mofkey,
    text={"verbosity": "low", "format": {"type": "json_schema", "name": "MOFAnswer", "strict": True, "schema": IDENTITY_SCHEMA}},
    store=False,
)
identity_answer_mofkey = json.loads(identity_response_mofkey.output_text)
print(json.dumps(identity_answer_mofkey, indent=2))

{
  "can_determine": false,
  "value": null
}

In [25]:
# REQUIRES_OPENAI_API_KEY
identity_results = pd.DataFrame([
    grade("cif", identity_expected["cif"], ground_truth_identity, identity_answer_cif),
    grade("mofjson", identity_expected["mofjson"], ground_truth_identity, identity_answer_mofjson),
    grade("mofid", identity_expected["mofid"], ground_truth_identity, identity_answer_mofid),
    grade("mofkey", identity_expected["mofkey"], ground_truth_identity, identity_answer_mofkey),
])
identity_results

,representation,expected_answerable,model_can_determine,model_value,ground_truth,correct
0,cif,True,True,C28H20N6O4,C10H8*5O4-2,False
1,mofjson,True,True,C10H8*5O4-2,C10H8*5O4-2,True
2,mofid,True,False,NaN,C10H8*5O4-2,False
3,mofkey,False,False,NaN,NaN,True

## 7) Category 4 (Symmetry (crystal system))

In [26]:
SYMMETRY_SCHEMA = make_answer_schema("string", "The crystal system, as a plain string (e.g. 'monoclinic').")
symmetry_expected = {"cif": True, "mofjson": True, "mofid": False, "mofkey": False}

raw_payload = {
    "lattice": doc["raw"]["lattice"],
    "atoms": [{"id": a["id"], "element": a["element"], "frac_xyz": a["frac_xyz"]} for a in doc["raw"]["atoms"]],
}

symmetry_prompt_cif = (
    f"Given the CIF file below, what crystal system does this structure belong to?\n\n{cif_text}"
    + CLOSING_INSTRUCTION
)
symmetry_prompt_mofjson = (
    f"Given the lattice and atomic coordinates below, what crystal system does this structure "
    f"belong to?\n\n{json.dumps(raw_payload, indent=2)}" + CLOSING_INSTRUCTION
)
symmetry_prompt_mofid = (
    f"A MOFid identifier for a metal-organic framework is given below. What crystal system "
    f"does this structure belong to?\n\n{mofid_string}" + CLOSING_INSTRUCTION
)
symmetry_prompt_mofkey = (
    f"A MOFkey identifier for a metal-organic framework is given below. What crystal system "
    f"does this structure belong to?\n\n{mofkey_string}" + CLOSING_INSTRUCTION
)

In [27]:
# REQUIRES_OPENAI_API_KEY
symmetry_response_cif = client.responses.create(
    model=MODEL,
    reasoning={"effort": "high", "summary": "detailed"},
    input=symmetry_prompt_cif,
    text={"verbosity": "low", "format": {"type": "json_schema", "name": "MOFAnswer", "strict": True, "schema": SYMMETRY_SCHEMA}},
    store=False,
)
symmetry_answer_cif = json.loads(symmetry_response_cif.output_text)
print(json.dumps(symmetry_answer_cif, indent=2))

{
  "can_determine": true,
  "value": "triclinic"
}

In [28]:
# REQUIRES_OPENAI_API_KEY
symmetry_response_mofjson = client.responses.create(
    model=MODEL,
    reasoning={"effort": "high", "summary": "detailed"},
    input=symmetry_prompt_mofjson,
    text={"verbosity": "low", "format": {"type": "json_schema", "name": "MOFAnswer", "strict": True, "schema": SYMMETRY_SCHEMA}},
    store=False,
)
symmetry_answer_mofjson = json.loads(symmetry_response_mofjson.output_text)
print(json.dumps(symmetry_answer_mofjson, indent=2))

{
  "can_determine": true,
  "value": "orthorhombic"
}

In [29]:
# REQUIRES_OPENAI_API_KEY
symmetry_response_mofid = client.responses.create(
    model=MODEL,
    reasoning={"effort": "high", "summary": "detailed"},
    input=symmetry_prompt_mofid,
    text={"verbosity": "low", "format": {"type": "json_schema", "name": "MOFAnswer", "strict": True, "schema": SYMMETRY_SCHEMA}},
    store=False,
)
symmetry_answer_mofid = json.loads(symmetry_response_mofid.output_text)
print(json.dumps(symmetry_answer_mofid, indent=2))

{
  "can_determine": false,
  "value": null
}

In [30]:
# REQUIRES_OPENAI_API_KEY
symmetry_response_mofkey = client.responses.create(
    model=MODEL,
    reasoning={"effort": "high", "summary": "detailed"},
    input=symmetry_prompt_mofkey,
    text={"verbosity": "low", "format": {"type": "json_schema", "name": "MOFAnswer", "strict": True, "schema": SYMMETRY_SCHEMA}},
    store=False,
)
symmetry_answer_mofkey = json.loads(symmetry_response_mofkey.output_text)
print(json.dumps(symmetry_answer_mofkey, indent=2))

{
  "can_determine": false,
  "value": null
}

In [31]:
# REQUIRES_OPENAI_API_KEY
symmetry_results = pd.DataFrame([
    grade("cif", symmetry_expected["cif"], ground_truth_crystal_system, symmetry_answer_cif),
    grade("mofjson", symmetry_expected["mofjson"], ground_truth_crystal_system, symmetry_answer_mofjson),
    grade("mofid", symmetry_expected["mofid"], ground_truth_crystal_system, symmetry_answer_mofid),
    grade("mofkey", symmetry_expected["mofkey"], ground_truth_crystal_system, symmetry_answer_mofkey),
])
symmetry_results

,representation,expected_answerable,model_can_determine,model_value,ground_truth,correct
0,cif,True,True,triclinic,orthorhombic,False
1,mofjson,True,True,orthorhombic,orthorhombic,True
2,mofid,False,False,NaN,NaN,True
3,mofkey,False,False,NaN,NaN,True

## 8) Summary

In [32]:
# REQUIRES_OPENAI_API_KEY
all_results = pd.concat([
    connectivity_results.assign(category="connectivity"),
    path_results.assign(category="net_path"),
    identity_results.assign(category="chemical_identity"),
    symmetry_results.assign(category="symmetry"),
], ignore_index=True)

all_results[["category", "representation", "expected_answerable", "model_can_determine", "model_value", "ground_truth", "correct"]]

,category,representation,expected_answerable,model_can_determine,model_value,ground_truth,correct
0,connectivity,cif,True,True,8.0,5.0,False
1,connectivity,mofjson,True,True,2.0,5.0,False
2,connectivity,mofid,False,True,2.0,NaN,False
3,connectivity,mofkey,False,False,NaN,NaN,True
4,net_path,cif,True,False,NaN,1.0,False
5,net_path,mofjson,True,True,1.0,1.0,True
6,net_path,mofid,False,False,NaN,NaN,True
7,net_path,mofkey,False,False,NaN,NaN,True
8,chemical_identity,cif,True,True,C28H20N6O4,C10H8*5O4-2,False
9,chemical_identity,mofjson,True,True,C10H8*5O4-2,C10H8*5O4-2,True
10,chemical_identity,mofid,True,False,NaN,C10H8*5O4-2,False
11,chemical_identity,mofkey,False,False,NaN,NaN,True
12,symmetry,cif,True,True,triclinic,orthorhombic,False
13,symmetry,mofjson,True,True,orthorhombic,orthorhombic,True
14,symmetry,mofid,False,False,NaN,NaN,True
15,symmetry,mofkey,False,False,NaN,NaN,True

In [16]:
import json
import pandas as pd

df = pd.read_csv("/Users/yong/projects/MoFJSON/model_responses/netpath/checked/gemini-3.7-flash-high_checked-1.csv.gz")
df = df[df["correct"].notna()]  # drop the 200 stale/unmatched rows

gt = {}
with open("/Users/yong/projects/MoFJSON/questions/netpath_questions_sample50.jsonl") as f:
    for line in f:
        row = json.loads(line)
        gt[str(row["uuid"])] = row["meta"]

wrong = df[(df.input_format == "mofjson") & (df.correct == False)].copy()
wrong["same_type"] = wrong["uuid"].map(lambda u: gt.get(str(u), {}).get("same_type"))
print(wrong[["ground_truth", "model_value", "same_type"]].to_string())
print(wrong["same_type"].value_counts(dropna=False))

     ground_truth  model_value  same_type
210           2.0            1       True
212           2.0           12       True
223           1.0            2       True
236           2.0            4       True
239           1.0            2       True
243           1.0            2       True
256           1.0            2       True
258           1.0            2       True
262           2.0            4       True
267           2.0            4       True
275           2.0            1       True
282           1.0            6       True
283           1.0            5       True
287           1.0            2       True
292           2.0            4       True
295           2.0            1       True
303           1.0            2       True
310           1.0            4       True
311           1.0            2       True
315           2.0            4       True
326           2.0            4       True
332           2.0            4       True
350           1.0            2       True
363           1.0            2       True
367           2.0            4       True
370           1.0            2       True
375           1.0            3       True
387           1.0            4       True
388           2.0            8       True
392           1.0            3       True
395           2.0            4       True
same_type
True    31
Name: count, dtype: int64